### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by BlessedPoplar** [LocalizeLimbusCompany/LLC_MOD_Toolbox#10]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

点击一键安装立刻弹出弹窗然后闪退。.NET6.0已装。
在思考是不是新电脑有什么必需架构没装，请教无上皮神。

### 日志文件

[LLCToolBox_log.txt](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/11728917/LLCToolBox_log.txt)

**Comment by Bright1192** [comment]
log内看起来没有有用信息
>点击一键安装立刻弹出弹窗然后闪退

弹窗内容是什么呢

**Comment by BlessedPoplar** [comment]
因为github错误还是自个网络错误没有发上来的说（？）


白杨馆长
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LocalizeLimbusCompany/LLC_MOD_Toolbox"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月13日(星期二) 上午9:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LocalizeLimbusCompany/LLC_MOD_Toolbox] Error report (Issue #10)





 
log内看起来没有有用信息
  
点击一键安装立刻弹出弹窗然后闪退
  
弹窗内容是什么呢

**Comment by Bright1192** [comment]
我似乎没有看到弹窗内容或者图片(

**Comment by BlessedPoplar** [comment]
白杨馆长
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LocalizeLimbusCompany/LLC_MOD_Toolbox"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月13日(星期二) 上午10:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LocalizeLimbusCompany/LLC_MOD_Toolbox] Error report (Issue #10)





 
我似乎没有看到弹窗内容或者图片(

**Comment by BlessedPoplar** [comment]
![error report](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/136393644/f63d2d93-4e31-42e5-adaf-f201c1c114b4)

**Comment by Bright1192** [comment]
看起来原因出现在你无法访问小皮的镜像站(怎么回事呢)，不过既然你可以发issue，那么解决方法也许是将第1个选项关掉第2个选项开启，这样就可以访问GitHub而不是镜像站

**Comment by BlessedPoplar** [comment]
![error report(1)](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/136393644/31428020-4d8c-4613-813d-b1ed2aad0e95)
这个是代理问题吗，还是什么其他问题

**Comment by Bright1192** [comment]
有点看不透，为什么无法访问/下载呢，曾小皮，救我呀@ZengXiaoPi
不过在他来解决你的问题之前或许你可以尝试进行手动安装(不过手动安装也要访问GitHub/镜像站来下载组件，看起来有点无解)

**Comment by ZengXiaoPi** [comment]
有些奇妙的，因为能正常ping到三个节点，但是为什么下不了就不太清楚了，尝试使用手动安装。

**Comment by ZengXiaoPi** [comment]
应当已经在v0.3.3修复。如果还有问题请重新打开此议题。

**Comment by hdidhalsdlasl** [comment]
![屏幕截图 2024-04-13 210948](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/166775132/eb24c603-8ae4-4f99-941d-de7495b06421)
请问这应该怎么解决
