### ISSUE TITLE
安装模组时报错

### ISSUE THREAD

**Issue by Alicepro** [LocalizeLimbusCompany/LLC_MOD_Toolbox#100]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

卸载了老模组，安装新的0.6.61版本汉化时报错

### 日志文件

[Log-20241213.log](https://github.com/user-attachments/files/18114940/Log-20241213.log)

### 截图

![26daf80f-691e-47e6-b921-6aa5fba72866](https://github.com/user-attachments/assets/3b8b0c2b-b992-4d32-ba09-76a464c27251)

**Comment by LeoGlacier** [comment]
![屏幕截图 2024-12-13 102353](https://github.com/user-attachments/assets/0e2170bb-d959-459c-8259-ec0c9ae277a7)

**Comment by Faize902** [comment]
![Uploading @4$VPM02F`MA$CA1Q6H{9(3.png…]()

**Comment by ZengXiaoPi** [comment]
重复议题，网络问题，尝试切换节点，关闭加速器
