### ISSUE TITLE
没有杀毒软件，文件夹缺失winhttp.dll文件

### ISSUE THREAD

**Issue by Epiphany1126** [LocalizeLimbusCompany/LLC_MOD_Toolbox#103]
### 在提问之前...

- [X] 我反馈的问题在零协会 BiliBili 动态没有相应近期公告
- [X] 我反馈的问题不属于已关闭/已解决的其它 Issue
- [X] 我使用的模组版本为最新版
- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等

### 问题描述

电脑没有自带的杀毒软件，windows安全中心也关闭，llc文件夹里和新下载的压缩包里都没有winhttp.dll文件，无法更新补丁

### 日志文件

[Log-20241229.log](https://github.com/user-attachments/files/18268325/Log-20241229.log)

### 截图

![fc12541dfa205f5cbcb4602a2ea6bf29](https://github.com/user-attachments/assets/bf416739-2c19-48b4-85eb-415ade5a8812)

**Comment by ZengXiaoPi** [comment]
请你开启模组。
