### ISSUE TITLE
一键安装失败

### ISSUE THREAD

**Issue by linwind123** [LocalizeLimbusCompany/LLC_MOD_Toolbox#11]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

无法使用工具箱的一键安装，在下载安装过程中失败

### 日志文件

[LLCToolBox_log.txt](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/11771782/LLCToolBox_log.txt)

### 截图

![KTCQVUWACTJP~~%AP LIPEX](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/136830925/18ec1ee2-ba6a-4bdd-8260-4e9a08c1381d)

**Comment by ZengXiaoPi** [comment]
你的limbus.determination.top被解析到了127.0.0.1吗？
请暂时使用手动安装。

**Comment by ZengXiaoPi** [comment]
无法复现，可能是因为dns问题，请尝试使用114dns。
