### ISSUE TITLE
已知bug

### ISSUE THREAD

**Issue by ZengXiaoPi** [LocalizeLimbusCompany/LLC_MOD_Toolbox#12]
注意，你不应该在这里回复你的任何问题，你不会得到任何帮助。

- ~~MelonLoader 无法使用更新功能~~ （0.3.4 fix）
  -  ~~表现为不论版本，自动跳过安装~~
  -  ~~原因为检查大于0.6.1后即跳过，应在使用MFL时检查api。~~
- ~~文档站地址错误~~ （0.3.4 fix）
- ~~Windows10 检测系统疑似无法使用？~~(bie not need)
- ~~版本号对不上~~(Who cares)

**Comment by RepresentationEmitter** [comment]
<img width="1280" alt="屏幕截图 2023-06-26 104212" src="https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/135411765/de254113-238b-4970-8aad-f4d9643546d0">
[新建 文本文档 (2).txt](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/11862613/2.txt)
请问有什么解决办法吗？

**Comment by Bright1192** [comment]
all clear?
