### ISSUE TITLE
下载模组本体时出现错误

### ISSUE THREAD

**Issue by xykwxy** [LocalizeLimbusCompany/LLC_MOD_Toolbox#13]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

一键安装下载模组本体（进度66%）时出现错误，无法安装模组本体，打开游戏出现Failed to Download Cpp2IL
手动安装模组本体后仍出现Failed to Download Cpp2IL

### 日志文件

[LLCToolBox_log.txt](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/11858713/LLCToolBox_log.txt)

### 截图

![image](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/137666853/4cba3bb5-8a9c-4b74-81f3-1736e5dda0d9)
![image](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/137666853/adebebf7-e603-4d02-b827-f83a2cc39121)

**Comment by ZengXiaoPi** [comment]
请尝试再次下载最新版的0.3.3。

**Comment by ZengXiaoPi** [comment]
因为你能够访问Github，如果仍然无法解决请暂时关闭Melonloader For LLC并打开从github下载。

**Comment by xykwxy** [comment]
感谢，在github下载后问题已解决
