### ISSUE TITLE
自动汉化安装工具无法使用

### ISSUE THREAD

**Issue by Knightj9291** [LocalizeLimbusCompany/LLC_MOD_Toolbox#14]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

之前使用均正常，今天使用自动汉化工具尝试更新翻译后无法一键安装与启动游戏，表现为安装时弹出错误对话框然后安装工具自动退出，启动游戏时弹错

### 日志文件

[LLCToolBox_log.txt](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/11924027/LLCToolBox_log.txt)

### 截图

启动游戏有弹窗
![QQ截图20220526111557](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/138268937/a73e757f-911a-48fb-bdd3-4beecc8d759f)

**Comment by ZengXiaoPi** [comment]
怎么绘事呢
![image](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/102937102/7a349abf-bbf7-46c5-9768-0c592760f1ea)

**Comment by Knightj9291** [comment]
我不知道呀。。我出问题以后就把游戏和汉化工具都卸载了，然后重新下载再装的

**Comment by Bright1192** [comment]
已修复

**Comment by Knightj9291** [comment]
你好，还是不行呀，老样子o.o
