### ISSUE TITLE
在Windows8.1上无法使用toolbox

### ISSUE THREAD

**Issue by xin-Furld** [LocalizeLimbusCompany/LLC_MOD_Toolbox#17]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我的系统是Windows8.1，这很明显符合系统要求，并且已经安装好了NET6.0，但在打开toolbox时，依然显示“汉化补丁不支持Windows7以及以下版本的windows! ”并让我安装NET6.0。但是如果直接下载汉化补丁的全量包并手动安装上去之后，又可以使用汉化包了，并且使用半个月之后并没有出现任何的bug。

### 日志文件

[Log-20230719.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/12094226/Log-20230719.log)

### 截图

![截图20230719182634](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/139969792/9a1eb938-6edd-4f39-8008-c427199fb72f)

**Comment by ZengXiaoPi** [comment]
看起来是因为检测的实际是Windows10导致的，至于.net6.0我个人不太清楚……
