### ISSUE TITLE
即使按照教程仍然出现白屏闪退问题

### ISSUE THREAD

**Issue by keyclka2424383** [LocalizeLimbusCompany/LLC_MOD_Toolbox#19]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

尽管加速了GitHub，依然出现了白屏后闪退且无报错的问题，并且网络并无任何问题（其他设备使用网络情况良好）

### 日志文件

[Latest(框架日志).log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/12183404/Latest.log)
[游戏日志.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/12183415/default.log)
抱歉我没有找到这个文件，但是我把两个生成的日志拖拽了进来，希望也可以，已经重装了几回了，目前的记录应该都是没有打开的

### 截图

![image](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/139748512/d66178c3-a583-48df-bfce-a53f5cd02992)

**Comment by Bright1192** [comment]
根据log，你并没有正确的加速GitHub
如果你不知道你在做什么请你使用安装器
