### ISSUE TITLE
即使加速依旧白屏闪退

### ISSUE THREAD

**Issue by keyclka2424383** [LocalizeLimbusCompany/LLC_MOD_Toolbox#21]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

已经使用了推荐的加速器加速Github仍然无法正常进入游戏，出现白屏闪退无报错的情况，说真的我不明白该怎么做，请求帮助。网络是没有问题的，其他软件并无连不上网的情况。

### 日志文件

[Log-20230728.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/12185766/Log-20230728.log)
希望这次的日志正确
[Latest(框架日志).log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/12185777/Latest.log)
我确实没有找到LLCToolBox_log.txt日志文件，在截图中提到了，请问是我哪里下载出了问题吗？

### 截图

![image](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/139748512/7c69c221-5c4e-4782-a47a-ad5523494a44)
![屏幕截图 2023-07-27 203013](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/139748512/b0a40113-20df-4372-b1e6-4b4bd8972197)
![屏幕截图 2023-07-28 001723](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/139748512/4effd15f-b871-4a9e-97a9-2613c8c4eb92)
![屏幕截图 2023-07-28 001653](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/139748512/7f920ac9-6f7f-40cd-9e38-d5fe61ef6955)
![image](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/139748512/3424eb11-4d3e-41a2-b9bb-f5ae1d144fba)

**Comment by ZengXiaoPi** [comment]
连接MelonLoader Remote API发生错误，使用MelonLoader For LLC

**Comment by keyclka2424383** [comment]
> 连接MelonLoader Remote API发生错误，使用MelonLoader For LLC

请问具体如何操作？
