### ISSUE TITLE
用toolbox下载还是手动下载补丁都无法成功应用汉化，运行窗口代码有飘红

### ISSUE THREAD

**Issue by valieeeee** [LocalizeLimbusCompany/LLC_MOD_Toolbox#22]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我用以前issue里面的方法重装了很多次，结果还是没办法正常打开melonloader，并且在之前补丁也可以正常工具箱安装正常运行，删除是因为游戏更新后打不开游戏了，删除后能正常运行，重新装补丁就没办法运行了，这是melonloader自身的原因还是我这边的网络问题？

### 日志文件

运行时弹出窗口后光标无法进行操作，只能关闭游戏

### 截图

![屏幕截图 2023-08-02 173639](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/141247493/913b00ff-e3cb-4bd0-953d-332cc009c598)

**Comment by ZengXiaoPi** [comment]
仅仅是白屏？

**Comment by ZengXiaoPi** [comment]
我建议你工具箱删除一次补丁，然后再安装一次。

**Comment by valieeeee** [comment]
用工具箱删过很多次了，还是这个问题

**Comment by valieeeee** [comment]
工具箱设置的选项吗？那个一直是开着的，我也试过不选melonloader for llc 选择从GitHub下载文件，还是没解决这个问题

**Comment by ZengXiaoPi** [comment]
算了，睡觉

**Comment by valieeeee** [comment]
枯了

**Comment by XiaHuaXH** [comment]
啊，这个白屏问题应当与网络无关，我在实际操作时发现尽管出现了白屏，在确保网络通常的情况下，模组框架也能正常配置然后进入游戏，并且目前没有解决白屏问题的先例
另外，强制关闭游戏似乎反映了你能够操纵系统，并且据我所知，即使强制关闭游戏也会有log生成，请你仔细地找一找游戏根目录以及melonloader文件夹下是否生成log

**Comment by XiaHuaXH** [comment]
你还可以尝试手动下载依赖库
2021.3.0.zip https://raw.githubusercontent.com/LavaGang/Unity-Runtime-Libraries/master/2021.3.0.zip 重命名为UnityDependencies_2021.3.0.zip
Cpp2IL-2022.1.0-pre-release.12-Windows-Netframework472.zip https://github.com/SamboyCoding/Cpp2IL/releases/download/2022.1.0-pre-release.10/Cpp2IL-2022.1.0-pre-release.10-Windows-Netframework472.zip 重命名为Cpp2IL_2022.1.0-pre-release.10.zip
以上两个文件均放入游戏根目录\MelonLoader\Dependencies\Il2CppAssemblyGenerator下

**Comment by valieeeee** [comment]
> 啊，这个白屏问题应当与网络无关，我在实际操作时发现尽管出现了白屏，在确保网络通常的情况下，模组框架也能正常配置然后进入游戏，并且目前没有解决白屏问题的先例 另外，强制关闭游戏似乎反映了你能够操纵系统，并且据我所知，即使强制关闭游戏也会有log生成，请你仔细地找一找游戏根目录以及melonloader文件夹下是否生成log

[Latest.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/12248117/Latest.log)
是有生成这个log，但是按照最后一条的方法下载依赖库还是没有作用

**Comment by ZengXiaoPi** [comment]
> > 啊，这个白屏问题应当与网络无关，我在实际操作时发现尽管出现了白屏，在确保网络通常的情况下，模组框架也能正常配置然后进入游戏，并且目前没有解决白屏问题的先例 另外，强制关闭游戏似乎反映了你能够操纵系统，并且据我所知，即使强制关闭游戏也会有log生成，请你仔细地找一找游戏根目录以及melonloader文件夹下是否生成log
> 
> [Latest.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/12248117/Latest.log) 是有生成这个log，但是按照最后一条的方法下载依赖库还是没有作用

关闭你的杀毒软件。
看起来除此以外没有问题了，因此关闭此议题。
