### ISSUE TITLE
安装汉化模组后依旧是未汉化的状态

### ISSUE THREAD

**Issue by GreatCatSoul** [LocalizeLimbusCompany/LLC_MOD_Toolbox#24]
情况有点特殊，机械硬盘炸了导致储存在里面的汉化模组与游戏都没了，但是系统盘还在，安装了新的硬盘后，重新安装了.net6.0 和汉化模组，也把汉化模组加入了杀毒软件的白名单，但启动游戏后并没有汉化内容，也么有出现汉化模组的弹窗。杀毒软件也没有提示，汉化模组也没有任何报错。

**Comment by GreatCatSoul** [comment]
[Log-20230811.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/12319233/Log-20230811.log)
[Log-20230811.log20230811.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/12319234/Log-20230811.log20230811.log)

**Comment by N071** [comment]
我居然复现了本问题……
稍等，请让我们查看我们的文件是否正常

**Comment by N071** [comment]
我们组内也复现了同样的问题。
不过，目前他们发现问题已经解决。
请您在安装完毕汉化模组后查看游戏根目录是否符合以下截图：
![image](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/128023427/456fde3d-a905-48d6-b45f-6cd4f0f903a9)
若不符合，则说明您的安装仍存在问题

**Comment by sumiemo** [comment]
<img width="486" alt="屏幕截图 2023-08-12 225623" src="https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/129023879/93b8b180-0bc0-49ea-b131-663089515c5e">
<img width="144" alt="屏幕截图 2023-08-13 163009" src="https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/129023879/3bf96646-05c0-4ff2-9069-af5276830321">
不管怎么安装都缺少图二文件，每个链接都试过了，也开了梯子。

**Comment by sumiemo** [comment]
[Uploading 框架日志.log…]()

**Comment by sumiemo** [comment]
[游戏日志.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/12329083/default.log)
