### ISSUE TITLE
安装时有概率安装失败

### ISSUE THREAD

**Issue by WJDFJKDSg** [LocalizeLimbusCompany/LLC_MOD_Toolbox#29]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

安装时有概率安装失败

### 日志文件

[Log-20230823.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/12414501/Log-20230823.log)

### 截图

![{83632786-E0BA-4d5d-951D-704A933D21F4}](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/139449438/bf97a96e-558b-49c4-a4f9-587a1a4feb86)

**Comment by ZengXiaoPi** [comment]
网络问题，**如果你不知道你在干什么，不要开启从Github下载**
