### ISSUE TITLE
模组未生效。无法首次运行模组，

### ISSUE THREAD

**Issue by wuyouwudao** [LocalizeLimbusCompany/LLC_MOD_Toolbox#30]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

大概是前天吧，在我一次打开电脑之后，从steam运行Linux company，然后突然发现没有模组的界面，也无法在游戏内正常使用模组的翻译，我怀疑是安装包出了问题，于是我把模组从安装器里面删除之后重新装，并没有修复该问题。
然后我把 Linux company本体全部删除，整个文件夹被我清空掉了，重新安装游戏本体，然后再次安装模组，却发现依旧无法成功运行模组。

### 日志文件

[框架日志.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/12485066/default.log)

**Comment by N071** [comment]
你的模组(和模组安装器)看起来已经严重过时，我们已不支持此过时版本。
请至[自动安装](https://www.zeroasso.top/docs/install/autoinstall)文档页面跟随我们的教程安装最新版模组安装器，并使用最新版安装器安装最新版模组。

**Comment by wuyouwudao** [comment]
> 你的模组(和模组安装器)看起来已经严重过时，我们已不支持此过时版本。 请至[自动安装](https://www.zeroasso.top/docs/install/autoinstall)文档页面跟随我们的教程安装最新版模组安装器，并使用最新版安装器安装最新版模组。

不不不，我刚看了一下这个日志，好像与我的不太相符合，我的安装器是这个，日志是只有这个剩下来了，很抱歉带来了误会
![image](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/126943042/394f79bf-57c2-4c7a-98ff-2d302d8c80c0)

**Comment by N071** [comment]
那么，也许是你的模组根本没有启动，而你将旧版本未删除的log发了上来。
我建议：
- 如果您可以使用网络代理服务，请在安装时使用全局代理使网络更加通畅
- 我明白长时间的排错不如一个迅速而无脑的解决方法。若您希望以较快的速度即刻重装模组，请试试[文件覆盖方案](https://www.zeroasso.top/docs/question#解决方案文件覆盖)

**Comment by N071** [comment]
最近因网络不可抗力出现的安装问题越来越多了，可以参考这篇关于[河南用户网络问题](https://b23.tv/sNRwF8y)的零协会公告

**Comment by wuyouwudao** [comment]
> 最近因网络不可抗力出现的安装问题越来越多了，可以参考这篇关于[河南用户网络问题](https://b23.tv/sNRwF8y)的零协会公告

**Comment by wuyouwudao** [comment]
> 那么，也许是你的模组根本没有启动，而你将旧版本未删除的log发了上来。 我建议：
> 
> * 如果您可以使用网络代理服务，请在安装时使用全局代理使网络更加通畅
> * 我明白长时间的排错不如一个迅速而无脑的解决方法。若您希望以较快的速度即刻重装模组，请试试[文件覆盖方案](https://www.zeroasso.top/docs/question#%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88%E6%96%87%E4%BB%B6%E8%A6%86%E7%9B%96)

我按照您的建议下载并尝试了文件覆盖方式，很遗憾，并没有启动成功，我不明白，我下载的文件应该是没有问题的，但就是打不开模组，很奇怪不是吗，我在想是否有种方法可以手动打开模组？？

**Comment by N071** [comment]
为了确认，请至游戏根目录比对您的文件完整性：
![E36A732C-8808-4A8C-94B5-5E730D0CFAAB](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/128023427/fc1faa75-6700-4cac-b9d8-1c268b8d7b38)

**Comment by wuyouwudao** [comment]
![image](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/126943042/9571617e-ee93-474b-a93c-ded87cb274dd)

**Comment by N071** [comment]
我想起我们组内有两例突然无法使用模组，而后无征兆恢复的情况。其中一例甚至发生在我们的一位主要开发者身上。他们当时也无法通过文件覆盖修复该问题，我们至今未能排错。

我并非模组主要开发者，因此我能提供的信息较为有限：
- 您通过“文件覆盖”方式安装的文件应当是不存在问题的
- 请尝试完全删除旧模组后重新使用“文件覆盖”方式
- 请尝试重启电脑后重新开启游戏
- ~或者，就像我们组内的两例情况一样等待魔法发生~

我也可以联系组内的主要开发者跟进此情况。

**Comment by wuyouwudao** [comment]
> 我想起我们组内有两例突然无法使用模组，而后无征兆恢复的情况。其中一例甚至发生在我们的一位主要开发者身上。他们当时也无法通过文件覆盖修复该问题，我们至今未能排错。
> 
> 我并非模组主要开发者，因此我能提供的信息较为有限：
> 
> * 您通过“文件覆盖”方式安装的文件应当是不存在问题的
> * 请尝试完全删除旧模组后重新使用“文件覆盖”方式
> * 请尝试重启电脑后重新开启游戏
> * ~或者，就像我们组内的两例情况一样等待魔法发生~
> 
> 我也可以联系组内的主要开发者跟进此情况。

其实我个人主要认为可能是启动优先级的问题，可能哈，我是说可能，因为我那一天是用steam启动的，我平常则是通过桌面上的快捷方式启动，可能用steam启动判定优先级，直接从游戏本体进行了启动，然后后面导致可能的确就是一直通过本体启动，而没有启动到模组，但模组具体的作用机制我并不了解，所以这只是我个人的一个小猜测。

**Comment by wuyouwudao** [comment]
唉，反正现在用不了模组了，我好伤心。

**Comment by ZengXiaoPi** [comment]
无法复现。

**Comment by N071** [comment]
您有可靠的网络代理服务吗？如果您能畅通无阻的使用国外提供的网络服务，我们可以尝试使用BepInEx最初的版本，而不是我们的特供版 来进一步排错

**Comment by wuyouwudao** [comment]
向您所说的那样，它神奇的自己恢复了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月31日(星期四) 晚上8:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LocalizeLimbusCompany/LLC_MOD_Toolbox] 模组未生效。无法首次运行模组， (Issue #30)





 
您有可靠的网络代理服务吗？如果您能畅通无阻的使用国外提供的网络服务，我们可以尝试使用BepInEx最初的版本，而不是我们的特供版 来进一步排错
