### ISSUE TITLE
安装后汉化脚本无法使用

### ISSUE THREAD

**Issue by sumiemo** [LocalizeLimbusCompany/LLC_MOD_Toolbox#31]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

刚下载的时候可以用，后面再怎么打开都没法用。

### 日志文件

[Latest(框架日志).log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/12505196/Latest.log)
[Player(游戏日志).log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/12505197/Player.log)

### 截图

<img width="638" alt="image" src="https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/129023879/19df30d5-a8e6-4628-9b5d-2714bbdfc71c">

**Comment by sumiemo** [comment]
求解QAQ

**Comment by sumiemo** [comment]
<img width="545" alt="image" src="https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/129023879/b0b4e436-0923-464d-9970-aecfdd825f23">

**Comment by sumiemo** [comment]
[Log-20230905.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/12517795/Log-20230905.log)

**Comment by N071** [comment]
我对模组代码方面了解不多，请稍等
我会联系其他开发者回复

**Comment by N071** [comment]
首先，保险起见：请问你的游戏安装路径内是否**存在中文字符**？

开发者反应你的Log看起来没有任何问题。这与你叙述的“无法打开模组”不符。
你是否进行了[文件覆盖操作](https://www.zeroasso.top/docs/question#%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88%E6%96%87%E4%BB%B6%E8%A6%86%E7%9B%96)而将文件覆盖中已有的log一同下载了？

**Comment by sumiemo** [comment]
> 首先，保险起见：请问你的游戏安装路径内是否**存在中文字符**？
> 
> 开发者反应你的Log看起来没有任何问题。这与你叙述的“无法打开模组”不符。 你是否进行了[文件覆盖操作](https://www.zeroasso.top/docs/question#%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88%E6%96%87%E4%BB%B6%E8%A6%86%E7%9B%96)而将文件覆盖中已有的log一同下载了？

中文路径没有，另一个要怎么处理，游戏和安装器卸了，装别的地方吗？

**Comment by N071** [comment]
也就是说你没有进行过文件覆盖操作吗？
请您直接回答这个问题：您有没有进行过文件覆盖操作。

若希望尝试[文件覆盖](https://www.zeroasso.top/docs/question#%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88%E6%96%87%E4%BB%B6%E8%A6%86%E7%9B%96)来解决问题，请严格按照文档站相应部分的指引进行操作。

**Comment by sumiemo** [comment]
> 也就是说你没有进行过文件覆盖操作吗？ 请您直接回答这个问题：**您有没有进行过文件覆盖操作？**
> 
> 若希望尝试[文件覆盖](https://www.zeroasso.top/docs/question#%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88%E6%96%87%E4%BB%B6%E8%A6%86%E7%9B%96)来解决问题，请严格按照文档站相应部分的指引进行操作。

中午试过，可以了，不过下午再登又没有了

**Comment by ZengXiaoPi** [comment]
暂时没有解决方案。

**Comment by ZengXiaoPi** [comment]
**你求我也没用，没有解决方法就是没有**

**Comment by N071** [comment]
也许您并不清楚本问题的具体情况。
事情是这样的：我们完全无法复现本问题，因此我们无法针对性的定位并解决本问题。不论我们看多少遍您提供的Log，我们都是不能解决这个问题的。

我们组内也有两例突然无法使用模组，而后无征兆恢复的情况。其中一例甚至发生在我们的一位主要开发者身上。他们当时也无法通过文件覆盖修复该问题，我们至今未能排错。

[Issue30](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/issues/30)的这位用户也遇到的同样情况。他也在一段时间后自动恢复了。

事实上，我们并不知道这个问题出现的原因，也不知道为什么大部分这样的问题都会奇迹般地恢复。您要知道，我们使用的BepInEx框架并不由我们自己开发，也正处于Beta测试版本。奇怪的问题确实是有可能发生的。
