### ISSUE TITLE
安装后汉化脚本无法使用

### ISSUE THREAD

**Issue by sumiemo** [LocalizeLimbusCompany/LLC_MOD_Toolbox#32]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

汉化脚本不运行QAQ

杀毒也进入白名单了
下载了，最新的安装器，手册上的方法都试过了

### 日志文件

[Log-20230905.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/12517813/Log-20230905.log)

### 截图

<img width="629" alt="image" src="https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/129023879/1215964f-f336-4c0c-9ca7-b84a99f55233">

**Comment by N071** [comment]
请在已有的[Issue31](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/issues/31)内继续讨论，无需发布新Issue。
