### ISSUE TITLE
开启“从GitHub下载文件”选项后工具箱不会下载bepinex

### ISSUE THREAD

**Issue by cothurn** [LocalizeLimbusCompany/LLC_MOD_Toolbox#33]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

这个问题其实是我在0.4.2版本里遇到的，但是0.4.4版本仍然可以复现
当设置为从github下载时：
![image](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/14202194/dc34d11b-f545-4d30-9d40-89ac1bdb994c)
工具箱提示安装完成后游戏根目录长这样，明显可以看出缺东西：
![image](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/14202194/25c65d20-378e-4e2a-8c81-f97abc1ea265)

### 日志文件

工具箱的log：
[Log-20230907.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/12555654/Log-20230907.log)

**Comment by ZengXiaoPi** [comment]
杀毒软件原因。

**Comment by ZengXiaoPi** [comment]
哦，看起来不太一样。。。

**Comment by ZengXiaoPi** [comment]
已修复
