### ISSUE TITLE
启动器升级V 0.5.0版本后安装报错

### ISSUE THREAD

**Issue by ZERO1999999** [LocalizeLimbusCompany/LLC_MOD_Toolbox#34]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

启动器升级V 0.5.0版本后汉化启动器报错，报错截图如下，尝试过多种办法，给以管理员模式运行，关闭杀毒软件，用翻墙软件均出现以下问题
![QQ图片20231003210748](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/146690246/dc9734b3-b463-422d-9314-e040d92f4e33)
![QQ图片20231003211059](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/146690246/77538a13-7770-4d04-a157-76da58895d0e)

### 日志文件

10.03，安装多次均出现异常
[Log-20231003.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/12792919/Log-20231003.log)

### 截图

![QQ图片20231003210748](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/146690246/f556ae01-7e73-4e18-a658-16fba7ced552)
![QQ图片20231003211059](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/146690246/ff8187d7-861c-40b4-b64f-330b374c192d)

### 还有别的吗？

操作系统  win10 64位

**Comment by ZERO1999999** [comment]
![image](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/146690246/8b241bd8-ea0f-48ae-a1cb-09200fa9746d)
按报错提示的文件位置查找到的文件夹为空，好像没有正确解压

**Comment by ZengXiaoPi** [comment]
好问题，明天试试修复一下

**Comment by ZengXiaoPi** [comment]
v0.5.1修复
