### ISSUE TITLE
汉化无法使用

### ISSUE THREAD

**Issue by motius13** [LocalizeLimbusCompany/LLC_MOD_Toolbox#35]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我成功地装载了安装器，在安装（用的一键安装）汉化mod后进入游戏却无法显示中文（仍显示英文)
BeplnEX能够唤出

### 日志文件

[Log-20231005.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/12813962/Log-20231005.log)
[Log-20231005.log20231005.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/12813964/Log-20231005.log20231005.log)
[Log-20231005.log20231005.log20231005.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/12813966/Log-20231005.log20231005.log20231005.log)

**Comment by N071** [comment]
感谢您的反馈：看起来我们的文件系统确有此问题，我们已经在修理。
我推荐两个解决方法：
- 如果您与GitHub连接状况良好，请在安装器设置页面打开“从GitHub下载文件”后重新安装。
- 采用[文件覆盖](https://www.zeroasso.top/docs/question#%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88%E6%96%87%E4%BB%B6%E8%A6%86%E7%9B%96)

**Comment by ZengXiaoPi** [comment]
正在进行一个新版本的制作

**Comment by ZengXiaoPi** [comment]
v0.5.2 修复了
