### ISSUE TITLE
工具箱压缩包被认为是病毒无法下载

### ISSUE THREAD

**Issue by Otonahi-Mirai** [LocalizeLimbusCompany/LLC_MOD_Toolbox#36]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我使用了官网的onedirve和github渠道，都报告有病毒无法安装

### 日志文件

无

### 截图

![image](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/62061255/ea3d4f19-124f-49c3-b697-f2a7ea89d049)

**Comment by N071** [comment]
您遇到的问题很可能是因为我们的下载链接目前还没有域名。我们当前没有为我们的服务器配置域名，但我们计划很快改善这一现状。在这之前，您可以选择继续下载，浏览器报毒不意味着不能下载。
