### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by 367xyx** [LocalizeLimbusCompany/LLC_MOD_Toolbox#38]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动安装和手动安装都会跳出相同的弹窗，找不到指定文件

### 日志文件

[Log-20231216.log20231216.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/13693061/Log-20231216.log20231216.log)
[Log-20231216.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/13693062/Log-20231216.log)

### 截图

![屏幕截图 2023-12-16 235549](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/154007461/2992da99-3442-49aa-b69f-0688a50bd004)

**Comment by ZengXiaoPi** [comment]
**请不要直接在压缩包中打开程序**
（要解压之后打开exe难道不是常识吗）

**Comment by 367xyx** [comment]
我就是解压后打开的LLC_MOD_Toolbox.exe啊
![屏幕截图 2023-12-17 001625](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/154007461/77baefb7-c2a2-411b-9427-aef018a8c809)

**Comment by N071** [comment]
> 我就是解压后打开的LLC_MOD_Toolbox.exe啊 ![屏幕截图 2023-12-17 001625](https://private-user-images.githubusercontent.com/154007461/291003517-77baefb7-c2a2-411b-9427-aef018a8c809.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3NDM4OTQsIm5iZiI6MTcwMjc0MzU5NCwicGF0aCI6Ii8xNTQwMDc0NjEvMjkxMDAzNTE3LTc3YmFlZmI3LWMyYTItNDExYi05NDI3LWFlZjAxOGE4YzgwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNlQxNjE5NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDgwN2Q1YzYxNDI3ZmJjYjgxNWNiM2U0ZTE2MzQzOTMxZGQ3MTkzMTE5NjIxMjUwNDBhMDNkOWIwOWNmOGY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vo53GLijjVeZCBFJHP-mHslmvecEnxfHWbZHqo5HJNA)

您的截图显示的是仍在WinRAR内部的文件，并非解压过后置于文件夹中的文件。请您选择“解压到”并解压文件到系统文件夹。不要直接打开Zip文件并运行其中exe文件。

**Comment by ZengXiaoPi** [comment]
~~被WinRAR气晕~~

**Comment by 367xyx** [comment]
感谢大佬们的解答，被自己蠢到了，多谢！
