### ISSUE TITLE
切换语言后闪退

### ISSUE THREAD

**Issue by CosmoChromE** [LocalizeLimbusCompany/LLC_MOD_Toolbox#39]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

进入游戏到达主页面，点击之后,经过短暂的connecting直接闪退

### 日志文件

<img width="1512" alt="截屏2023-12-31 08 44 19" src="https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/151953018/95dda393-40bc-4eec-b3c7-ab6d2337f47f">
今天的log没有文件

### 还有别的吗？

macbookpro 使用 parallels desktop（win10）进行游戏，一般没有问题

**Comment by Bright1192** [comment]
未复现此问题

**Comment by N071** [comment]
我们的模组一般不会影响网络连接性和游戏本身运行情况，还请确认是否是网络或其他原因造成的

**Comment by CosmoChromE** [comment]
点击工具箱的关闭补丁选项后回归正常

**Comment by N071** [comment]
> 点击工具箱的关闭补丁选项后回归正常

有尝试过卸载补丁后进行重装吗？

**Comment by ZengXiaoPi** [comment]
由于无法复现以及没有提供日志，本问题无法解决。
