### ISSUE TITLE
【安装问题】关于LLC_MOD的前置运行的NET框架的问题

### ISSUE THREAD

**Issue by mhmoonh** [LocalizeLimbusCompany/LLC_MOD_Toolbox#40]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

是用的官网的自动下载 NET框架是按教程安装的 用的是自动安装 之前第五章出来之前都能用 把旧的汉化包卸载完再安装更新的之后就直接安装不上了TT
![捕11](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/156423556/a6553eac-0b52-428e-ab30-07bdea4212d8)

### 日志文件

好像没有日志抱歉TT 如果没有日志解决不了就算了很抱歉打扰TT

### 还有别的吗？

已经下过6.0的框架了 自动汉化提醒要下4.8.1的框架点了是自动跳转 但系统不支持4.8.1
是win10

**Comment by ZengXiaoPi** [comment]
你猜我是windows几
![image](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/102937102/f0224b5e-225e-4f20-9285-eb6becdcb1ca)

**Comment by ZengXiaoPi** [comment]
尝试使用 https://go.microsoft.com/fwlink/?linkid=2088631

**Comment by N071** [comment]
很抱歉我们的文档站没有在安装器6.0更新之后及时同步关于前置框架的问题。现在我们的安装器需要.NET4.8，而不是.NET6.0。
现在，Windows专业版和家庭版最低需要版本1607才能安装.NET4.8框架。请您确认您的Windows10系统版本，如果版本过低是无法解决的，只能通过您升级系统，再安装.NET4.8框架来解决。

如果您不希望升级系统，我们推荐您尝试[手动安装](https://www.zeroasso.top/docs/install/install)或[文件覆盖](https://www.zeroasso.top/docs/question#%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88%E6%96%87%E4%BB%B6%E8%A6%86%E7%9B%96)

**Comment by ZengXiaoPi** [comment]
检查系统版本：
1. ![image](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/102937102/376830f0-6ff6-461f-bcf9-76bd7f55f5d0)
2. ![image](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/102937102/0c50f782-1bbf-4d5e-b46c-0afcad86a3f6)

**Comment by ZengXiaoPi** [comment]
我好像指错了，但是发上面的版本号（例如21H2）也可以
~~而且我好像多截了点东西~~

**Comment by mhmoonh** [comment]
十分感谢答复！！！换了链接给的NET框架然后手动安装就完全可以用了！！辛苦汉化组了！！！特别感谢！！
