### ISSUE TITLE
在切换语言后重新进入游戏会闪退。

### ISSUE THREAD

**Issue by wujiu5** [LocalizeLimbusCompany/LLC_MOD_Toolbox#41]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

游戏中从中文切换其他语言后（英文，日文）关闭并重新开启游戏，游戏在主界面（touch to start）无响应并在点击后闪退。重新安装工具箱对问题无帮助。进行文件覆盖后，bepinex窗口不再出现但游戏可以以英文、日文等语言正常运行。

### 日志文件

[Log-20240127.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/14072833/Log-20240127.log)

### 截图

![QQ截图20240127211717](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/157901624/dff9714c-6d04-4d6a-bf87-fbfac79654e4)

**Comment by ZengXiaoPi** [comment]
尝试更换源为mirror ghproxy下载模组。

**Comment by ZengXiaoPi** [comment]
关于切换语言闪退，我们是没有复现出来的，所以无法解决。

**Comment by wujiu5** [comment]
> 尝试更换源为mirror ghproxy下载模组。

问题已解决，感谢
