### ISSUE TITLE
无法启动工具箱

### ISSUE THREAD

**Issue by LaseRb314** [LocalizeLimbusCompany/LLC_MOD_Toolbox#42]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

打开游戏可以唤起BepInEx，已尝试过重新安装工具箱及net6.0框架、手动安装各模组以及使用管理员模式运行工具箱，皆无法启动工具箱。

### 日志文件

[Tips.txt](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/14120408/Tips.txt)
好像并没有生成描述的日志文件，目录下的txt文件只有这一份。我不太懂这些请见谅。

### 还有别的吗？

版本为win11 22H2，64位操作系统。操作系统版本为22621.3007。

**Comment by ZengXiaoPi** [comment]
尝试安装.net4.8框架

**Comment by N071** [comment]
1. 如果可以，请您提供无法启动工具箱的报错截图。
2. 工具箱Log文件在此文件夹内，请查看其内是否有Log。
![image](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/128023427/4f2767b0-bca4-4135-ba4d-bbbc74d7889b)
3. 当前，最新版工具箱依赖 .Net 4.8 框架，而非 .Net 6.0 框架。

**Comment by LaseRb314** [comment]
感谢回复。
工具箱没有产生报错窗口，双击后无任何响应。
由于我前段时间一直使用手动安装更新汉化，卸载了工具箱导致没有log文件产生。之前的log丢失了。
已安装net4.8框架，但工具箱仍无响应。

**Comment by ZengXiaoPi** [comment]
无法复现。

**Comment by sd12504123** [comment]
@LaseRb314 ，問題可能在於防毒軟件將其隔離，從隔離區還原即可

**Comment by LaseRb314** [comment]
感谢回复。
卸载了防毒软件，重新下载后仍然无法启动工具箱。
最开始我是使用工具箱进行汉化更新，约2个月后才产生无法启动的情况。第一次无法启动工具箱的时间是在2023年12月底，更新了工具箱后。
非常感谢，各位费心了。

**Comment by ZengXiaoPi** [comment]
不清楚，手动安装
