### ISSUE TITLE
加载游戏有控制台弹出但是会闪退

### ISSUE THREAD

**Issue by 9s4hu** [LocalizeLimbusCompany/LLC_MOD_Toolbox#43]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

你好，我原先能够使用汉化模组，但1月31日杀毒软件阻止游戏启动，在选择信任且删除汉化模组后游戏可正常启动。重装模组后打开游戏可以弹出控制台，但加载一段时间后闪退，使用文件覆盖安装后仍有同样的问题
用文件覆盖开始安装后弹出截图所示弹窗
![屏幕截图 2024-02-01 161533](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/158659365/1f0e25bb-f358-4f25-ae5b-8d4c6cf32fed)
游戏根目录里没有两个log
![屏幕截图 2024-02-03 105059](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/158659365/b610f4b6-70ca-4dea-a94a-79b23009be97)
验证游戏完整性，删除游戏并重装，清除缓存后仍不能解决问题

### 日志文件

[Uploading Log-20240203.log…]()
[ErrorLog.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/14149482/ErrorLog.log)
[LogOutput.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/14149483/LogOutput.log)

### 还有别的吗？

操作系统为win11(x64)
最初安装汉化模组时杀毒软件没有拦截

**Comment by ZengXiaoPi** [comment]
尝试直接关闭杀毒软件。

**Comment by ZengXiaoPi** [comment]
且工具箱日志并未上传

**Comment by 9s4hu** [comment]
[Log-20240203.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/14149651/Log-20240203.log)是这个吗
杀毒软件好像是预装的，关不掉

**Comment by N071** [comment]
> 但1月31日杀毒软件阻止游戏启动，在选择信任且删除汉化模组后游戏可正常启动
抱歉我没有很读懂这句话。您的意思是杀毒软件阻止了汉化模组，然后您删除了汉化模组吗？还是说您先信任了汉化模组，又删除了汉化模组？
另外，哪怕是Windows内置的Windows Defender也能被您暂时关闭。关闭的杀毒软件将不会扫描您的文件。参考微软的教程：[关闭 Windows 安全中心中的Defender 防病毒保护](https://support.microsoft.com/zh-cn/windows/%E5%85%B3%E9%97%AD-windows-%E5%AE%89%E5%85%A8%E4%B8%AD%E5%BF%83%E4%B8%AD%E7%9A%84defender-%E9%98%B2%E7%97%85%E6%AF%92%E4%BF%9D%E6%8A%A4-99e6004f-c54c-8509-773c-a4d776b77960#:~:text=%E5%85%B3%E9%97%AD%20Windows%20%E5%AE%89%E5%85%A8%E4%B8%AD%E5%BF%83%E4%B8%AD%E7%9A%84Defender%20%E9%98%B2%E7%97%85%E6%AF%92%E4%BF%9D%E6%8A%A4%201%20%E9%80%89%E6%8B%A9%20%22%E5%BC%80%E5%A7%8B%20%22%EF%BC%8CWindows,3%20%E5%B0%86%E2%80%9C%20%E5%AE%9E%E6%97%B6%E4%BF%9D%E6%8A%A4%20%E2%80%9D%E5%88%87%E6%8D%A2%E4%B8%BA%E2%80%9C%20%E5%85%B3%20%E2%80%9D%E3%80%82%20%E6%B3%A8%E6%84%8F%EF%BC%8C%E8%AE%A1%E5%88%92%E7%9A%84%E6%89%AB%E6%8F%8F%E5%B0%86%E7%BB%A7%E7%BB%AD%E8%BF%90%E8%A1%8C%E3%80%82%20%E4%BD%86%E6%98%AF%EF%BC%8C%E5%9C%A8%E4%B8%8B%E6%AC%A1%E8%AE%A1%E5%88%92%E6%89%AB%E6%8F%8F%E4%B9%8B%E5%89%8D%EF%BC%8C%E4%B8%8D%E4%BC%9A%E6%89%AB%E6%8F%8F%E4%B8%8B%E8%BD%BD%E6%88%96%E5%AE%89%E8%A3%85%E7%9A%84%E6%96%87%E4%BB%B6%E3%80%82)

**Comment by 9s4hu** [comment]
抱歉没有表述清楚，是杀毒软件阻止打开游戏（此时无控制台弹出），选择信任后有控制台弹出但是闪退，删除汉化模组后能正常打开游戏。现在是把杀毒软件都关闭了，不过还是会闪退
