### ISSUE TITLE
校验Hash失败

### ISSUE THREAD

**Issue by WJDFJKDSg** [LocalizeLimbusCompany/LLC_MOD_Toolbox#44]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

校验Hash失败更换节点后仍出现此问题

### 日志文件

[Log-20240215.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/14291209/Log-20240215.log)

### 截图

![22e32cb215145d68e6d1a88c7ea2b9db](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/139449438/6347e3f5-5f8e-4540-921c-00f5db0a9c76)

**Comment by N071** [comment]
我们进行版本更新的过程中可能会产能此类问题。请现在试着再尝试一下？
