### ISSUE TITLE
游戏内切换语言后重进游戏闪退

### ISSUE THREAD

**Issue by VainGloryFive** [LocalizeLimbusCompany/LLC_MOD_Toolbox#45]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

用工具箱再次尝试时自动安装显示游戏正在运行中无法汉化，手动安装未生效，将工具箱和游戏卸载重装都未解决该问题

### 日志文件

[
[Log-20240307.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/14532824/Log-20240307.log)
[Log-20240308.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/14532825/Log-20240308.log)
](url)

### 截图

![66UL0NV HZO54KK_FM WQJ](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/162659690/c369d48e-51f3-432c-925f-a75b7910b274)

**Comment by VainGloryFive** [comment]
补丁删除后再用工具箱安装就显示这个

**Comment by ZengXiaoPi** [comment]
duplicate of #41
