### ISSUE TITLE
遊戲中漢化正常但工具箱無法開啟

### ISSUE THREAD

**Issue by sd12504123** [LocalizeLimbusCompany/LLC_MOD_Toolbox#46]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

遊戲中漢化正常，但無法開啟壓縮檔中工具箱exe檔案，exe檔案名被變更為exe.config

### 日志文件

![螢幕擷取畫面 2024-03-24 191037](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/164742448/f1e99d66-3d17-4496-9769-e53495e9be65)

### 截图

![螢幕擷取畫面 2024-03-24 190904](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/164742448/2e3288ca-
![螢幕擷取畫面 2024-03-24 191002](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/164742448/5a02c622-12fd-46dc-b7da-9e2992757a1d)
8366-4a5f-95f9-41f99aca5478)
![螢幕擷取畫面 2024-03-24 191037](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/164742448/9a3da89d-2d7b-4ed9-a626-ba2b9b4a306d)

**Comment by sd12504123** [comment]
已解決，問題在於防毒軟件將其隔離，將更改防毒軟件識別該檔案的類型後並從隔離區還原即可

**Comment by ZengXiaoPi** [comment]
实际上.exe.config是工具箱的配置文件（）
就是程序被杀毒图图了
