### ISSUE TITLE
使用漢化後遊戲打開就閃退

### ISSUE THREAD

**Issue by greatIshmael** [LocalizeLimbusCompany/LLC_MOD_Toolbox#47]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用漢化後遊戲進入直接閃退 啟動畫面都沒有 黑屏的時候直接閃退 換遊戲本身的語言沒問題

### 日志文件

[LogOutput.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/14852636/LogOutput.log)
[Log-20240403.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/14852637/Log-20240403.log)

**Comment by ZengXiaoPi** [comment]
是不是有切换语言

**Comment by greatIshmael** [comment]
是 切換語言了






                       
原始邮件
                       
                     

发件人："曾小皮-ZengXiaoPi"< ***@***.*** &gt;;

发件时间：2024/4/4 11:40

收件人："LocalizeLimbusCompany/LLC_MOD_Toolbox"< ***@***.*** &gt;;

抄送人："greatIshmael"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [LocalizeLimbusCompany/LLC_MOD_Toolbox] 使用漢化後遊戲打開就閃退 (Issue #47)




 
是不是有切换语言

**Comment by ZengXiaoPi** [comment]
请卸载汉化补丁后重新安装。
