### ISSUE TITLE
v0.6.3版本设置 开启\关闭模组功能无法正常使用

### ISSUE THREAD

**Issue by sevune** [LocalizeLimbusCompany/LLC_MOD_Toolbox#48]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

下载完汉化补丁后无法正常开启关闭模组，该功能在删除汉化补丁后可正常使用
已重装多次，问题无法解决，Session4 更新前该功能可正常运行

### 日志文件

[Log-20240418.log](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/15021239/Log-20240418.log)
记录时间：2024-04-18 15:16:16,813

### 截图

![无标题](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/80512750/9e8e4f36-6284-4e15-8f73-14b458ba967b)

### 还有别的吗？

已上传截图中详细信息内容

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.IO.IOException: 当文件已存在时，无法创建该文件。

   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   在 LLC_MOD_Toolbox.MainPage.uiButton1_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 Sunny.UI.UIControl.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.8.9181.0 built by: NET481REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
LLC_MOD_Toolbox
    程序集版本:0.6.3.0
    Win32 版本:0.6.3
    基本代码:file:///C:/Users/Sevune/Downloads/Compressed/Limbus/LLC_MOD_Toolbox/LLC_MOD_Toolbox.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.8.9181.0 built by: NET481REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.8.9220.0 built by: NET481REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
SunnyUI
    程序集版本:3.6.3.0
    Win32 版本:3.6.3.0
    基本代码:file:///C:/Users/Sevune/Downloads/Compressed/Limbus/LLC_MOD_Toolbox/SunnyUI.DLL
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.8.9220.0 built by: NET481REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
log4net
    程序集版本:2.0.15.0
    Win32 版本:2.0.15.0
    基本代码:file:///C:/Users/Sevune/Downloads/Compressed/Limbus/LLC_MOD_Toolbox/log4net.DLL
----------------------------------------
SunnyUI.Common
    程序集版本:3.6.3.0
    Win32 版本:3.6.3.0
    基本代码:file:///C:/Users/Sevune/Downloads/Compressed/Limbus/LLC_MOD_Toolbox/SunnyUI.Common.DLL
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
SharpConfig
    程序集版本:3.2.9.1
    Win32 版本:3.2.9.1
    基本代码:file:///C:/Users/Sevune/Downloads/Compressed/Limbus/LLC_MOD_Toolbox/SharpConfig.DLL
----------------------------------------
System.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.resources.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
7z.NET
    程序集版本:1.0.3.0
    Win32 版本:1.0.3.0
    基本代码:file:///C:/Users/Sevune/Downloads/Compressed/Limbus/LLC_MOD_Toolbox/7z.NET.DLL
----------------------------------------
System.Net.Http
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

**Comment by ZengXiaoPi** [comment]
是个问题，但目前还无法解决

**Comment by ZengXiaoPi** [comment]
新版本将移除此功能。
