### ISSUE TITLE
远程服务器返回错误:(500)

### ISSUE THREAD

**Issue by Hydrojoker** [LocalizeLimbusCompany/LLC_MOD_Toolbox#51]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

汉化补丁安装时会出现（应该不会是我网的问题吧……虽然我家的网络质量一直都挺差的。）
报错码跟零协官网常见错误里的报错码不一样，提供的两种方法都没有用。
噢我知道了，Steam++背大锅，工具箱如果是开着Steam++的话就会报错。

### 日志文件

[Log-20240625.log](https://github.com/user-attachments/files/15967354/Log-20240625.log)

### 截图

![Uploading Image_1719301655565.jpg…]()

**Comment by N071** [comment]
Steam++的服务有时较差，不过网络嘛……就是会出现奇怪的问题。
我个人建议尝试Steamcommunity302，更加稳定。

另外，工具箱下载报错的话，可以去设置页面手动选择不同节点来下载。我们默认的是通过OneDriveForBusiness下载，换个其他下载方式或许能解决问题。

**Comment by ZengXiaoPi** [comment]
```
记录时间：2024-06-25 15:40:52,984 日志级别：INFO  - 描述：从: http://alist.zeroasso.top:5244/d/od/LimbusLocalize_BIE_v0.6.40.7z下载文件。
记录时间：2024-06-25 15:40:53,123 日志级别：ERROR - 描述：出现了问题： System.Net.WebException: 远程服务器返回错误: (500) 内部服务器错误。
   在 System.Net.WebClient.OpenRead(Uri address)
   在 LLC_MOD_Toolbox.MainPage.GetLimbusLocalizeHash()
   在 LLC_MOD_Toolbox.MainPage.<installButton_Click>d__8.MoveNext()
```
问题在于，工具箱由于不明原因**不会**使用`https://node.zeroasso.top`，而是使用`http://alist.zeroasso.top:5244`，很奇怪，因为这是一个早就被弃用的域名。后续更新会修复此问题。
