### ISSUE TITLE
zeroasso.top拒绝连接导致无法使用

### ISSUE THREAD

**Issue by jiangWAW** [LocalizeLimbusCompany/LLC_MOD_Toolbox#52]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

准备安装汉化补丁时发现无法安装并弹出截图（1）两次，尝试登入zeroasso.top时发现zeroasso.top拒绝了链接（如截图（2）），附上管理人界面（截图（3）），以此证明我真的热爱着project moon的作品，真的热爱着limbus company，证明我真的需要零协会的汉化

### 日志文件

[Log-20240701.log](https://github.com/user-attachments/files/16047570/Log-20240701.log)
打开文档便能看见报错

### 截图

![图片 1](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/174291546/bba363e4-f355-48f8-87a
![图片 1](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/174291546/f1ca527f-13ec-4b4b-ab65-875f623528a9)
b-5afb5a0099ba)
![图片 1](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/174291546/943c4168-16ff-4766-92b5-20029328f612)
![图片 1](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/174291546/d130aee0-6765-4e9f-be6c-0a065e39389e)

### 还有别的吗？

已经确认网络连接正常，代理情况如截图（4）所示，windows版本为windows 10 企业版

**Comment by jiangWAW** [comment]
![图片 1](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/174291546/9e1916f0-5e1f-4742-b29f-e7b2cdb1080d)

**Comment by ZengXiaoPi** [comment]
请看bilibili动态。

**Comment by jiangWAW** [comment]
辛苦了，谢谢
