### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by couhioe** [LocalizeLimbusCompany/LLC_MOD_Toolbox#53]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

表现在更新到0.6.8bate版汉化软件后启动没有报错弹窗，游戏内无汉化，没有之前与游戏一起启动的命令行窗口。已卸载汉化重新安装数遍，重新安装游戏，删除c盘下的资源包后重新安装游戏及汉化两遍，以管理员运行汉化软件进行下载完毕后仍无汉化

### 日志文件

[Log-20240710.log](https://github.com/user-attachments/files/16157486/Log-20240710.log)

### 截图

以下是按要求展示的安装流程GitHub下载
![image](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/175196319/4acb9c94-38f1-42e2-a545-84f7ff5b3b25)
解压致游戏安装目录
![image](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/175196319/35140de1-a383-4532-b177-dd7107f78051)
管理员运行
![image](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/175196319/b69e684a-074b-4ca7-ab20-1286c4c59a7e)
开始安装
![image](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/175196319/81a0b86b-44ee-4d4f-935f-47d45b873cdf)
启动
![image](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/175196319/caf3ab6f-9cad-45cd-94c8-3739cefaf028)
没有汉化
![image](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/175196319/9759e2e4-c1be-4621-992a-f9f258e6ef98)

**Comment by couhioe** [comment]
![image](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/175196319/a664d3fb-ee34-469c-962d-d70f6a26222f)
补个图

**Comment by ZengXiaoPi** [comment]
https://zeroasso.top/docs/question/#%E6%A8%A1%E7%BB%84%E6%AD%A3%E5%B8%B8%E5%AE%89%E8%A3%85%E4%BD%86%E6%89%93%E5%BC%80%E6%B8%B8%E6%88%8F%E6%97%A0%E6%8E%A7%E5%88%B6%E5%8F%B0%E5%BC%B9%E5%87%BA%E4%B8%8D%E5%94%A4%E8%B5%B7bepinex

**Comment by couhioe** [comment]
> https://zeroasso.top/docs/question/#%E6%A8%A1%E7%BB%84%E6%AD%A3%E5%B8%B8%E5%AE%89%E8%A3%85%E4%BD%86%E6%89%93%E5%BC%80%E6%B8%B8%E6%88%8F%E6%97%A0%E6%8E%A7%E5%88%B6%E5%8F%B0%E5%BC%B9%E5%87%BA%E4%B8%8D%E5%94%A4%E8%B5%B7bepinex

![image](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/175196319/d4f780a5-743f-4d00-afa6-835525ec6b01)
还是未唤起BepInEx，倒霉
