### ISSUE TITLE
新版本汉化工具箱打不开

### ISSUE THREAD

**Issue by icysadness** [LocalizeLimbusCompany/LLC_MOD_Toolbox#54]
最新版本的工具箱，打开后提示我缺少net framework 4.7.2 ,但是我的电脑中已有更高版本的4.8.1
![IMG20240710211712](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/175284258/10233dcf-6fc0-4077-a0f9-893e616659f6)
![IMG20240710210339](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/175284258/3d039b21-58b2-4ae0-9548-600e4324db19)
![Uploading IMG20240710210334.jpg…]()

**Comment by ZengXiaoPi** [comment]
这就像是.net6.0不能向下兼容4.8一样
