### ISSUE TITLE
换了beta工具箱无法使用

### ISSUE THREAD

**Issue by IPME111** [LocalizeLimbusCompany/LLC_MOD_Toolbox#55]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

beat工具箱无法使用，开启旧版下载方式提示校验Hash失败

### 日志文件

[Log-20240711.log](https://github.com/user-attachments/files/16179939/Log-20240711.log)

### 截图

![QQ图片20240711231055](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/175331191/a6e93f32-7760-4120-b3a8-f2a3de639081)

![QQ图片20240711231101](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/175331191/db2449fe-fe05-4567-8996-079ff0cf0f4e)

**Comment by ZengXiaoPi** [comment]
在即将发布的新版本将会修复。
