### ISSUE TITLE
安装器Bate版无法使用

### ISSUE THREAD

**Issue by WHMEIOUING** [LocalizeLimbusCompany/LLC_MOD_Toolbox#56]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

点击应用后，首先弹出
![QQ_1720745129163](https://github.com/user-attachments/assets/3eaf85f4-8cfb-45e1-9f09-24cc237d4494)
点击继续后安装，会弹出三个报错

### 日志文件

[Log-20240712.log](https://github.com/user-attachments/files/16185760/Log-20240712.log)

### 还有别的吗？

Windows 10

**Comment by LIVELESS086** [comment]
[Log-20240718.log](https://github.com/user-attachments/files/16279426/Log-20240718.log)

确实如上所说出现以上问题
怀疑是网络问题
但有时正常

顺便一提   官网有一半时间
也拒接
是自家网络问题吗
请帮我一下   谢谢 @WHMEIOUING

**Comment by ZengXiaoPi** [comment]
更换节点。
