### ISSUE TITLE
工具箱版本v0.6.8 测试版  工具箱启动时和自动安装时报错 

### ISSUE THREAD

**Issue by Rose-qiuye** [LocalizeLimbusCompany/LLC_MOD_Toolbox#57]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在今天（7/18）第一次使用这个工具箱，游戏未安装汉化，工具箱启动时报错（截图与详细信息在下面），自动安装汉化时报错
目前已尝试过www.zeroasso.top/docs/question中的解决办法，并没能解决问题

### 日志文件

[
[Log-20240718.log](https://github.com/user-attachments/files/16281242/Log-20240718.log)
](url)
[Log-20240718.log20240718.log](https://github.com/user-attachments/files/16281246/Log-20240718.log20240718.log)

### 截图

![QQ截图20240718175439](https://github.com/user-attachments/assets/43273912-0917-4589-87dd-f8c06b21b65f)
![QQ截图20240718175614](https://github.com/user-attachments/assets/93346894-280d-4eb8-bb3d-e78d1477cb98)

### 还有别的吗？

系统：Win11 Pro 23H2 64位

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 无法从传输连接中读取数据: 远程主机强迫关闭了一个现有的连接。。 ---> System.Net.Sockets.SocketException: 远程主机强迫关闭了一个现有的连接。
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   在 System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   在 System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   在 System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   在 System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest, Boolean renegotiation)
   在 System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest, Boolean renegotiation)
   在 System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   在 System.Net.TlsStream.CallProcessAuthentication(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   在 System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   在 System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   在 System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.WebClient.OpenRead(Uri address)
   在 LLC_MOD_Toolbox_MeowVer.Main.CheckToolboxUpdate(String version) 位置 C:\Users\17032\source\repos\LLC_MOD_Toolbox_MeowVer\LLC_MOD_Toolbox_MeowVer\Main.cs:行号 620
   在 LLC_MOD_Toolbox_MeowVer.Main.InitToolBox() 位置 C:\Users\17032\source\repos\LLC_MOD_Toolbox_MeowVer\LLC_MOD_Toolbox_MeowVer\Main.cs:行号 48
   在 LLC_MOD_Toolbox_MeowVer.Main.Main_Load(Object sender, EventArgs e) 位置 C:\Users\17032\source\repos\LLC_MOD_Toolbox_MeowVer\LLC_MOD_Toolbox_MeowVer\Main.cs:行号 42
   在 System.Windows.Forms.Form.OnLoad(EventArgs e)
   在 System.Windows.Forms.Form.OnCreateControl()
   在 System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   在 System.Windows.Forms.Control.CreateControl()
   在 System.Windows.Forms.Control.WmShowWindow(Message& m)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   在 System.Windows.Forms.ContainerControl.WndProc(Message& m)
   在 System.Windows.Forms.Form.WmShowWindow(Message& m)
   在 System.Windows.Forms.Form.WndProc(Message& m)
   在 Sunny.UI.UIForm.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.8.9181.0 built by: NET481REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
LLC_MOD_Toolbox_MeowVer
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///C:/Users/Lenovo/Downloads/LLC_MOD_Toolbox/LLC_MOD_Toolbox/LLC_MOD_Toolbox_MeowVer.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.8.9181.0 built by: NET481REL1LAST_C
    基本代码:file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
SunnyUI
    程序集版本:3.6.7.0
    Win32 版本:3.6.7.0
    基本代码:file:///C:/Users/Lenovo/Downloads/LLC_MOD_Toolbox/LLC_MOD_Toolbox/SunnyUI.DLL
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.8.9220.0 built by: NET481REL1LAST_C
    基本代码:file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
log4net
    程序集版本:2.0.17.0
    Win32 版本:2.0.17.0
    基本代码:file:///C:/Users/Lenovo/Downloads/LLC_MOD_Toolbox/LLC_MOD_Toolbox/log4net.DLL
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.8.9220.0 built by: NET481REL1LAST_C
    基本代码:file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
SunnyUI.Common
    程序集版本:3.6.7.0
    Win32 版本:3.6.7.0
    基本代码:file:///C:/Users/Lenovo/Downloads/LLC_MOD_Toolbox/LLC_MOD_Toolbox/SunnyUI.Common.DLL
----------------------------------------
Newtonsoft.Json
    程序集版本:13.0.0.0
    Win32 版本:13.0.3.27908
    基本代码:file:///C:/Users/Lenovo/Downloads/LLC_MOD_Toolbox/LLC_MOD_Toolbox/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.CSharp
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0
    基本代码:file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.resources.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

**Comment by saibuyi233** [comment]
我也是这样改成旧版下载方式就好了

**Comment by ZengXiaoPi** [comment]
请尝试使用新版工具箱。

**Comment by ZengXiaoPi** [comment]
请尝试使用新版工具箱。
