### ISSUE TITLE
在使用0.6.8工具箱在开启出现异常、使用时出现问题

### ISSUE THREAD

**Issue by aptx4869q** [LocalizeLimbusCompany/LLC_MOD_Toolbox#58]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在开启最新版工具箱时出现异常提示

![Snipaste_2024-08-10_21-19-36](https://github.com/user-attachments/assets/49ce56ab-3677-4925-a1f4-e9ea1c3ac282)

按照手动安装说明检查文件时，并未发现缺失（应该？）

![Snipaste_2024-08-10_21-18-23](https://github.com/user-attachments/assets/36bd673f-9aa2-4991-b590-72f9256a1290)
![Snipaste_2024-08-10_21-18-40](https://github.com/user-attachments/assets/7e76ae3e-53c1-4a6e-9d14-ff29011a5463)

在安装汉化时出现如下异常

![Snipaste_2024-08-10_21-28-26](https://github.com/user-attachments/assets/e6fb8785-359e-4cac-9fe5-16a490276c2f)
![Snipaste_2024-08-10_21-28-34](https://github.com/user-attachments/assets/f86e2eff-dcbc-41a5-af97-a6b775c7967f)

在多次尝试过程中也会出现如下异常：

![Snipaste_2024-08-10_21-30-39](https://github.com/user-attachments/assets/3a36fb32-7be1-48e2-94eb-de11413455a5)
![Snipaste_2024-08-10_21-30-46](https://github.com/user-attachments/assets/f6059857-39e5-4852-bbf6-5d9ecb771c85)
![Snipaste_2024-08-10_21-30-32](https://github.com/user-attachments/assets/e7eb75c2-3c38-4380-80b4-cb8c908bef7b)

此问题在尝试过手动安装，重装工具箱，卸载模组，重装游戏等尝试后均未解决，希望大佬们能予以指出问题所在

### 日志文件

记录时间：2024-08-10 21:28:14,780 日志级别：INFO  - 描述：————NEW LOG————
记录时间：2024-08-10 21:28:14,786 日志级别：INFO  - 描述：工具箱版本：0.6.8
记录时间：2024-08-10 21:28:14,786 日志级别：INFO  - 描述：使用自动查找边狱公司方法。
记录时间：2024-08-10 21:28:14,786 日志级别：INFO  - 描述：在根目录找到了之前获取的路径，检查可用性。
记录时间：2024-08-10 21:28:14,787 日志级别：INFO  - 描述：路径可用，返回路径。
记录时间：2024-08-10 21:28:14,787 日志级别：INFO  - 描述：边狱公司路径：D:\Program Files (x86)\Steam\steamapps\common\Limbus Company
记录时间：2024-08-10 21:28:14,790 日志级别：INFO  - 描述：正在检查工具箱更新。
记录时间：2024-08-10 21:28:14,790 日志级别：INFO  - 描述：从镜像检查。
记录时间：2024-08-10 21:28:17,998 日志级别：INFO  - 描述：开始安装。
记录时间：2024-08-10 21:28:18,010 日志级别：INFO  - 描述：已进入安装BepInEx流程。
记录时间：2024-08-10 21:28:18,010 日志级别：INFO  - 描述：检测到正确BepInEx。
记录时间：2024-08-10 21:28:18,011 日志级别：INFO  - 描述：已进入TMP流程。
记录时间：2024-08-10 21:28:18,643 日志级别：INFO  - 描述：开始安装模组。
记录时间：2024-08-10 21:28:18,643 日志级别：INFO  - 描述：获取模组标签。
记录时间：2024-08-10 21:28:19,135 日志级别：INFO  - 描述：汉化模组最后标签为： v0.6.46
记录时间：2024-08-10 21:28:19,135 日志级别：INFO  - 描述：获取模组标签。
记录时间：2024-08-10 21:28:19,311 日志级别：INFO  - 描述：汉化模组最后标签为： v0.6.46
记录时间：2024-08-10 21:28:19,311 日志级别：INFO  - 描述：最后模组版本： v0.6.46
记录时间：2024-08-10 21:28:19,312 日志级别：INFO  - 描述：DownloadFileAutoAsync File: LimbusLocalize_BIE_v0.6.46.7zPath: D:\Program Files (x86)\Steam\steamapps\common\Limbus Company\LimbusLocalize_BIE.7z
记录时间：2024-08-10 21:28:19,312 日志级别：INFO  - 描述：正在DownloadFileAsync方法。
记录时间：2024-08-10 21:28:19,312 日志级别：INFO  - 描述：使用New下载方式。从https://node.zeroasso.top/d/od/LimbusLocalize_BIE_v0.6.46.7z下载到D:\Program Files (x86)\Steam\steamapps\common\Limbus Company\LimbusLocalize_BIE.7z
记录时间：2024-08-10 21:28:19,999 日志级别：ERROR - 描述：出现了问题：
System.Net.WebException: 远程服务器返回错误: (502) 错误的网关。
   在 System.Net.WebClient.OpenRead(Uri address)
   在 LLC_MOD_Toolbox_MeowVer.Main.GetURLText(String Url) 位置 C:\Users\17032\source\repos\LLC_MOD_Toolbox_MeowVer\LLC_MOD_Toolbox_MeowVer\Main.cs:行号 563
记录时间：2024-08-10 21:28:28,378 日志级别：ERROR - 描述：出现了问题：
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 无法对 null 引用执行运行时绑定
   在 CallSite.Target(Closure , CallSite , Object )
   在 System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   在 LLC_MOD_Toolbox_MeowVer.Main.GetLimbusLocalizeHash() 位置 C:\Users\17032\source\repos\LLC_MOD_Toolbox_MeowVer\LLC_MOD_Toolbox_MeowVer\Main.cs:行号 350
   在 LLC_MOD_Toolbox_MeowVer.Main.<InstallMod>d__16.MoveNext() 位置 C:\Users\17032\source\repos\LLC_MOD_Toolbox_MeowVer\LLC_MOD_Toolbox_MeowVer\Main.cs:行号 183
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 LLC_MOD_Toolbox_MeowVer.Main.<InstallButton_Click>d__13.MoveNext() 位置 C:\Users\17032\source\repos\LLC_MOD_Toolbox_MeowVer\LLC_MOD_Toolbox_MeowVer\Main.cs:行号 72
记录时间：2024-08-10 21:28:36,196 日志级别：INFO  - 描述：安装完成。

记录时间：2024-08-10 21:30:24,587 日志级别：INFO  - 描述：————NEW LOG————
记录时间：2024-08-10 21:30:24,593 日志级别：INFO  - 描述：工具箱版本：0.6.8
记录时间：2024-08-10 21:30:24,593 日志级别：INFO  - 描述：使用自动查找边狱公司方法。
记录时间：2024-08-10 21:30:24,593 日志级别：INFO  - 描述：在根目录找到了之前获取的路径，检查可用性。
记录时间：2024-08-10 21:30:24,593 日志级别：INFO  - 描述：路径可用，返回路径。
记录时间：2024-08-10 21:30:24,593 日志级别：INFO  - 描述：边狱公司路径：D:\Program Files (x86)\Steam\steamapps\common\Limbus Company
记录时间：2024-08-10 21:30:24,597 日志级别：INFO  - 描述：正在检查工具箱更新。
记录时间：2024-08-10 21:30:24,597 日志级别：INFO  - 描述：从镜像检查。
记录时间：2024-08-10 21:30:26,443 日志级别：INFO  - 描述：开始安装。
记录时间：2024-08-10 21:30:26,454 日志级别：INFO  - 描述：已进入安装BepInEx流程。
记录时间：2024-08-10 21:30:26,454 日志级别：INFO  - 描述：检测到正确BepInEx。
记录时间：2024-08-10 21:30:26,455 日志级别：INFO  - 描述：已进入TMP流程。
记录时间：2024-08-10 21:30:34,616 日志级别：ERROR - 描述：出现了问题。
System.Net.WebException: 远程服务器返回错误: (502) 错误的网关。
   在 System.Net.WebClient.OpenRead(Uri address)
   在 LLC_MOD_Toolbox_MeowVer.Main.CheckChineseFontAssetUpdate(String version, Boolean IsGithub, String& tag) 位置 C:\Users\17032\source\repos\LLC_MOD_Toolbox_MeowVer\LLC_MOD_Toolbox_MeowVer\Main.cs:行号 656
记录时间：2024-08-10 21:30:34,617 日志级别：INFO  - 描述：开始安装模组。
记录时间：2024-08-10 21:30:34,618 日志级别：INFO  - 描述：获取模组标签。
记录时间：2024-08-10 21:30:34,740 日志级别：ERROR - 描述：出现了问题：
System.Net.WebException: 远程服务器返回错误: (502) 错误的网关。
   在 System.Net.WebClient.OpenRead(Uri address)
   在 LLC_MOD_Toolbox_MeowVer.Main.GetURLText(String Url) 位置 C:\Users\17032\source\repos\LLC_MOD_Toolbox_MeowVer\LLC_MOD_Toolbox_MeowVer\Main.cs:行号 563
记录时间：2024-08-10 21:30:41,184 日志级别：ERROR - 描述：出现了问题：
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 LLC_MOD_Toolbox_MeowVer.Main.GetLatestLimbusLocalizeVersion() 位置 C:\Users\17032\source\repos\LLC_MOD_Toolbox_MeowVer\LLC_MOD_Toolbox_MeowVer\Main.cs:行号 548
   在 LLC_MOD_Toolbox_MeowVer.Main.<InstallMod>d__16.MoveNext() 位置 C:\Users\17032\source\repos\LLC_MOD_Toolbox_MeowVer\LLC_MOD_Toolbox_MeowVer\Main.cs:行号 173
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 LLC_MOD_Toolbox_MeowVer.Main.<InstallButton_Click>d__13.MoveNext() 位置 C:\Users\17032\source\repos\LLC_MOD_Toolbox_MeowVer\LLC_MOD_Toolbox_MeowVer\Main.cs:行号 72
记录时间：2024-08-10 21:30:49,256 日志级别：INFO  - 描述：安装完成。

### 截图

除以上描述中所展示的截图，另附开启工具箱时遇到的异常的详细信息
![Snipaste_2024-08-10_21-35-08](https://github.com/user-attachments/assets/e86ba9f5-af7f-4a1f-bb22-8f761fb33d56)

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.Net.WebException: 远程服务器返回错误: (502) 错误的网关。
   在 System.Net.WebClient.OpenRead(Uri address)
   在 LLC_MOD_Toolbox_MeowVer.Main.CheckToolboxUpdate(String version) 位置 C:\Users\17032\source\repos\LLC_MOD_Toolbox_MeowVer\LLC_MOD_Toolbox_MeowVer\Main.cs:行号 620
   在 LLC_MOD_Toolbox_MeowVer.Main.InitToolBox() 位置 C:\Users\17032\source\repos\LLC_MOD_Toolbox_MeowVer\LLC_MOD_Toolbox_MeowVer\Main.cs:行号 48
   在 LLC_MOD_Toolbox_MeowVer.Main.Main_Load(Object sender, EventArgs e) 位置 C:\Users\17032\source\repos\LLC_MOD_Toolbox_MeowVer\LLC_MOD_Toolbox_MeowVer\Main.cs:行号 42
   在 System.Windows.Forms.Form.OnLoad(EventArgs e)
   在 System.Windows.Forms.Form.OnCreateControl()
   在 System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   在 System.Windows.Forms.Control.CreateControl()
   在 System.Windows.Forms.Control.WmShowWindow(Message& m)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   在 System.Windows.Forms.ContainerControl.WndProc(Message& m)
   在 System.Windows.Forms.Form.WmShowWindow(Message& m)
   在 System.Windows.Forms.Form.WndProc(Message& m)
   在 Sunny.UI.UIForm.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.8.9261.0 built by: NET481REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
LLC_MOD_Toolbox_MeowVer
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///D:/%E4%B8%8B%E8%BD%BD/LocalizeLimbusModInstaller/LLC_MOD_Toolbox/LLC_MOD_Toolbox_MeowVer.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.8.9251.0 built by: NET481REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
SunnyUI
    程序集版本:3.6.7.0
    Win32 版本:3.6.7.0
    基本代码:file:///D:/%E4%B8%8B%E8%BD%BD/LocalizeLimbusModInstaller/LLC_MOD_Toolbox/SunnyUI.DLL
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.8.9261.0 built by: NET481REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
log4net
    程序集版本:2.0.17.0
    Win32 版本:2.0.17.0
    基本代码:file:///D:/%E4%B8%8B%E8%BD%BD/LocalizeLimbusModInstaller/LLC_MOD_Toolbox/log4net.DLL
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.8.9261.0 built by: NET481REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
SunnyUI.Common
    程序集版本:3.6.7.0
    Win32 版本:3.6.7.0
    基本代码:file:///D:/%E4%B8%8B%E8%BD%BD/LocalizeLimbusModInstaller/LLC_MOD_Toolbox/SunnyUI.Common.DLL
----------------------------------------
Newtonsoft.Json
    程序集版本:13.0.0.0
    Win32 版本:13.0.3.27908
    基本代码:file:///D:/%E4%B8%8B%E8%BD%BD/LocalizeLimbusModInstaller/LLC_MOD_Toolbox/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.CSharp
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.resources.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

### 还有别的吗？

无

**Comment by ZengXiaoPi** [comment]
网络问题。
