### ISSUE TITLE
工具箱（v1.0.0）闪退

### ISSUE THREAD

**Issue by bugtheworld** [LocalizeLimbusCompany/LLC_MOD_Toolbox#59]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

打开工具箱后，出现工具箱页面一段时间后（期间工具箱不可交互），工具箱闪退，从Log看应该是游戏安装目录的问题，疑似我前几天把游戏换了一个位置导致的。

### 日志文件

[Log-20240830.log](https://github.com/user-attachments/files/16808761/Log-20240830.log)

**Comment by ZengXiaoPi** [comment]
https://www.zeroasso.top/docs/question/#%E5%B7%A5%E5%85%B7%E7%AE%B1%E5%9C%A8%E5%90%AF%E5%8A%A8%E6%97%B6%E6%97%A0%E5%93%8D%E5%BA%94%E5%90%8E%E9%97%AA%E9%80%80
