### ISSUE TITLE
系统报错：出现了问题，访问被拒绝

### ISSUE THREAD

**Issue by Qiwen1020** [LocalizeLimbusCompany/LLC_MOD_Toolbox#6]
在点击一键安装之后就出现了这个弹窗，点击这个弹窗的确定之后，汉化补丁工具箱就闪退了，请问下该怎么解决？谢谢大佬
![捕获](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/135927282/569e356b-e40f-4ada-a611-115e1b8220cc)

**Comment by Bright1192** [comment]
建议先检查一下是否关闭了杀毒软件或者是否启动了游戏，如果仍然出现这个问题的话将安装器目录下的LLCToolBox_log.txt文件上传至此

**Comment by Qiwen1020** [comment]
谢谢大佬，太尴尬了，确实是因为游戏没彻底关闭所导致的
