### ISSUE TITLE
下载补丁报错

### ISSUE THREAD

**Issue by tiaojiangxianyu** [LocalizeLimbusCompany/LLC_MOD_Toolbox#61]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

安装汉化补丁时报错

### 日志文件

[Log-20240904.log](https://github.com/user-attachments/files/16869373/Log-20240904.log)

### 截图

![报错截图](https://github.com/user-attachments/assets/06e26d07-1933-47dc-a2b5-77ec56d6f72a)

**Comment by zayika2** [comment]
我也遇到一样的问题，在设置里切换一下节点就可以了，看了下日志这边https://node.zeroasso.top/d/od/BepInEx-IL2CPP-x64.7z下载的BepInEx-IL2CPP-x64.7z文件存在问题，解压不了，我去地址那边看了下
![image](https://github.com/user-attachments/assets/5b5c28b0-4912-49d3-bdfd-fd7b4fd82add)
这边好像没有BepInEx-IL2CPP-x64.7z这个文件。

**Comment by ZengXiaoPi** [comment]
更换节点即可解决。
