### ISSUE TITLE
这是一个标题

### ISSUE THREAD

**Issue by KloidinSpace** [LocalizeLimbusCompany/LLC_MOD_Toolbox#62]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在下载新版工具箱之后点击安装出现了这个提示，在关闭杀毒软件并且重新下载之后依然出现了这个问题，然后一会之后出现了这样的报错

### 日志文件

[Log-20240906.log](https://github.com/user-attachments/files/16903315/Log-20240906.log)

### 截图

![QQ图片20240906132646](https://github.com/user-attachments/assets/2283040c-bf91-4d7c-b7c5-710873e480ea)
![QQ图片20240906132632](https://github.com/user-attachments/assets/2820412f-14db-4c92-a84f-e7c773f386c0)

**Comment by ZengXiaoPi** [comment]
网络问题，请尝试使用`Github直连`
