### ISSUE TITLE
效验hash失败

### ISSUE THREAD

**Issue by ldldbak** [LocalizeLimbusCompany/LLC_MOD_Toolbox#63]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

已经换过多个节点以及重启和直连，都显示这个错误框

### 日志文件

[Log-20240906.log](https://github.com/user-attachments/files/16906700/Log-20240906.log)

### 截图

![错误2](https://github.com/user-attachments/assets/1f7797a2-f1d6-46a4-bd33-ddaafaf13bc4)

**Comment by WindancerNanami** [comment]
提供一个解决方案，切换一下节点（不一定是我用的这个）：
![image](https://github.com/user-attachments/assets/ef020820-879b-4fd8-a3de-4dd5f56790d7)

**Comment by WindancerNanami** [comment]
> 提供一个解决方案，切换一下节点（不一定是我用的这个）： ![image](https://private-user-images.githubusercontent.com/91819547/365152463-ef020820-879b-4fd8-a3de-4dd5f56790d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MjM2NTcsIm5iZiI6MTcyNTYyMzM1NywicGF0aCI6Ii85MTgxOTU0Ny8zNjUxNTI0NjMtZWYwMjA4MjAtODc5Yi00ZmQ4LWEzZGUtNGRkNWY1Njc5MGQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDExNDkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5Zjk3ODViNWNlMWUzMGQ5Y2E4YThmNzZjYjc3NGViZjg5OTY4YzVlMjRkOTA4OWIwMWEyZGNkMWNhY2Y5NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pTfZ5K6t9avyLLf_-iPJdPkMG0Ny1czw7hL8TxSeMu8)

补充：先点击设置，设置里面切换节点

**Comment by ZengXiaoPi** [comment]
应该已经修复了。
