### ISSUE TITLE
自动安装时报错

### ISSUE THREAD

**Issue by Aitib** [LocalizeLimbusCompany/LLC_MOD_Toolbox#65]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在NET8.0已经修复过的情况下再打开工具箱自动安装依旧会弹出报错信息（如log所示），在这之前的游戏汉化不受影响，也不影响游玩。最后通过手动安装安装了最新汉化，手动安装之后又启动了一次工具箱就没有报错弹窗了，不过看log时间貌似问题依旧存在？只是不解决也不影响游玩罢了。

### 日志文件

[Log-20240907.log](https://github.com/user-attachments/files/16920533/Log-20240907.log)

**Comment by Aitib** [comment]
更正：手动安装完成之后再打开工具箱依旧有报错弹窗。

**Comment by ZengXiaoPi** [comment]
不知道怎么修。
