### ISSUE TITLE
下载了最新版本的自动更新，但是在安装时出现了winhttp.dll不存在的说明

### ISSUE THREAD

**Issue by voilame** [LocalizeLimbusCompany/LLC_MOD_Toolbox#66]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我已关闭杀毒软件，查看过winhttp.dll确实存在，重启过电脑，用管理员模式打开，但是还是不行

### 日志文件

[Log-20240908.log](https://github.com/user-attachments/files/16920703/Log-20240908.log)

### 截图

![989(XD J6OYM__2CARWA(P](https://github.com/user-attachments/assets/163a8326-8707-4c1c-b8c5-2090d321416a)

### 还有别的吗？

设备名称	vooila
处理器	AMD Ryzen 7 5800H with Radeon Graphics            3.20 GHz
机带 RAM	16.0 GB (15.9 GB 可用)
设备 ID	6B9E88CF-770C-4431-A723-1FC8389BCBD1
产品 ID	00342-30474-72557-AAOEM
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入
版本	Windows 11 家庭中文版
版本号	23H2
安装日期	‎2023/‎2/‎10
操作系统版本	22631.4037
序列号	PF3HR9E4
体验	Windows Feature Experience Pack 1000.22700.1027.0

**Comment by ZengXiaoPi** [comment]
卸载后重新安装试试。
