### ISSUE TITLE
新版工具箱在自动安装时报错

### ISSUE THREAD

**Issue by phosphoever** [LocalizeLimbusCompany/LLC_MOD_Toolbox#67]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

尝试了重装电脑重启以及更换节点，还是报错（）

### 日志文件

[Log-20240909.log](https://github.com/user-attachments/files/16923050/Log-20240909.log)

### 截图

![屏幕截图 2024-09-09 010723](https://github.com/user-attachments/assets/9e00fc6a-fbd9-43ff-9dac-d1eef5f1c5b0)

**Comment by voilame** [comment]
啊，解决了，我在工具箱里把整个汉化文件全部卸载再重装就可以了，可能是原来的文件里有错误阻止了安装

**Comment by phosphoever** [comment]
> 啊，解决了，我在工具箱里把整个汉化文件全部卸载再重装就可以了，可能是原来的文件里有错误阻止了安装

呜呜试过了似乎还是不行

**Comment by phosphoever** [comment]
> 啊，解决了，我在工具箱里把整个汉化文件全部卸载再重装就可以了，可能是原来的文件里有错误阻止了安装

呜呜试过了似乎还是不行

**Comment by mucketguct** [comment]
@phosphoever 有另外一则修复成功的反馈是，遇到这种情况后，在对照“手动安装”页面的文件列表、手动卸载了所有汉化文件后，再重新安装，然后解决了此问题，如果还不行的话也可以试试手动卸载啦，祝顺利啦
