### ISSUE TITLE
汉化后无法启动游戏

### ISSUE THREAD

**Issue by 0674925** [LocalizeLimbusCompany/LLC_MOD_Toolbox#68]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

安装汉化后启动游戏报错

### 日志文件

[框架日志.log](https://github.com/user-attachments/files/17054468/default.log)
[游戏日志.log](https://github.com/user-attachments/files/17054469/default.log)

### 截图

![屏幕截图 2024-09-19 141232](https://github.com/user-attachments/assets/261916fc-b833-45b7-8156-b0eb5dd19c79)

**Comment by 0674925** [comment]
尝试换了台设备安装以及手动安装，都是同样的问题，蚌埠住了

**Comment by N071** [comment]
您似乎下载了错误的版本，您正在使用过时的安装器或模组（MelonLoader版本）。
请您重新检查您的版本，并换用正确的、由我们提供的下载渠道。

**Comment by ZengXiaoPi** [comment]
> 您似乎下载了错误的版本，您正在使用过时的安装器或模组（MelonLoader版本）。 请您重新检查您的版本，并换用正确的、由我们提供的下载渠道。

这并不是MelonLoader版本，而是MelonLoader之前的BepInEx版本
