### ISSUE TITLE
启动安装器与安装时弹出错误

### ISSUE THREAD

**Issue by BRSter** [LocalizeLimbusCompany/LLC_MOD_Toolbox#69]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

启动后弹出弹窗，点击确定后可以使用。但即便调了节点后，点击自动安装后会稳定卡在下载字体。就算自己下载字体丢进文件夹也无法使用。

### 日志文件

[Log-20240921.log](https://github.com/user-attachments/files/17082989/Log-20240921.log)

### 截图

![image](https://github.com/user-attachments/assets/9ce63e5e-53d4-46bf-85db-1fb423e68dc0)
![image](https://github.com/user-attachments/assets/b929c3e9-d299-429d-8052-325ede748319)

**Comment by ZengXiaoPi** [comment]
尝试更换节点。
