### ISSUE TITLE
McFee先斬後奏,我無法直接允許修改dll

### ISSUE THREAD

**Issue by fly81317** [LocalizeLimbusCompany/LLC_MOD_Toolbox#70]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我使用的防火牆是麥克菲
![image](https://github.com/user-attachments/assets/b3b191a1-59b6-476e-875f-3b65190cf1b1)
安裝漢化版工具箱和NET.8之後
我用電腦啟動後先出現黑色指令頁面
然後dll就被麥克菲隔離了
我不知道要怎麼做到永久允許
我平時都用手機玩,是因為想自己看人格故事才用電腦啟動的(我是劇情跳過大師)

### 日志文件

[另存記錄檔.zip](https://github.com/user-attachments/files/17191877/default.zip)

### 还有别的吗？

win11

**Comment by ZengXiaoPi** [comment]
把杀毒软件关闭就好了，你也可以找软件的客服寻求帮助。

**Comment by N071** [comment]
很抱歉，我们对其他的杀毒软件并无更多了解……这在我们的控制范围之外。我们无法绕过其安全程序。
关于其他软件造成的问题，还您请寻找关于其的帮助，或者咨询其维护人员
