### ISSUE TITLE
System.Net.Http.HttpRequestException: The SSL connection could not be established

### ISSUE THREAD

**Issue by hongye3056** [LocalizeLimbusCompany/LLC_MOD_Toolbox#71]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在大概半个月前突然出现这个问题, 删了重装工具箱仍然出现错误

### 日志文件

[Log-20240930.log](https://github.com/user-attachments/files/17197530/Log-20240930.log)

### 截图

![QQ20240930-195018](https://github.com/user-attachments/assets/9a509c95-f83e-4dd4-88c7-1e24882198cb)

**Comment by ZengXiaoPi** [comment]
网络问题，无解
