### ISSUE TITLE
启动器打开后几秒自动闪退   按照提供的解决办法自己写的游戏启动路径还是不行

### ISSUE THREAD

**Issue by qingfeng6897** [LocalizeLimbusCompany/LLC_MOD_Toolbox#74]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

从官网提供的那个Onedrive下载地址下载的启动器  启动几秒就自动闪退了  删了重新安装 自己写游戏启动路径啥都不行
另一个GitHub下载路径  解压出来里面没exe文件  只有俩后缀为csproj和sln的文件（跟别人对比了一下 总是缺点文件  应该是得先运行再下载的吧）

### 日志文件

[Log-20241003.log](https://github.com/user-attachments/files/17239894/Log-20241003.log)

### 截图

![QQ_1727936274752](https://github.com/user-attachments/assets/be1d3098-86e7-45cf-a742-8e2cba1a2a98)
![QQ_1727936430581](https://github.com/user-attachments/assets/385f6606-821a-4222-b0bd-ecc5da112c6e)

### 还有别的吗？

![QQ_1727936378705](https://github.com/user-attachments/assets/516c3a36-6230-4622-9e3a-5b34ea65b8b6)

**Comment by N071** [comment]
OneDrive和GitHub上的启动器文件没有实质性区别，另外您从GitHub下载的是源码而不是启动器（下载错了），如果您仍然信不过OneDrive方面的话请去“Release”界面才能下载到真正的启动器。

和其他人的文件区别不是您下载文件缺失的问题。一些文件是首次运行后生成的，所以有一些不太重要的区别不必担心。

问一下您之前有成功运行过v1.0.0以上的安装器吗？
- 如果没有，可能是您的系统兼容性问题，或者是您写的路径**不对/有语法错误/忘记保存**？
![image](https://github.com/user-attachments/assets/e93fdff5-e4b6-426f-b3bc-6f32fc48f6de)
- 如果有，这个问题就……比较玄学，可能也跟系统有关，其他人也曾有过突然无法使用的类似情况，可以稍等几天后再试试。


---
另外如果您急用模组，推荐参考模组的[手动安装](https://www.zeroasso.top/docs/install/install)方式。

**Comment by qingfeng6897** [comment]
我是在https://www.zeroasso.top/docs/install/autoinstall这个官网给的两个下载地址都下载的&nbsp; 说是两边都是mod工具箱 但github那个路径下是源文件&nbsp; （听别人说又跑到github网页把自安装版和普通压缩包又都下载了一遍 还是都不能打开）
咱最近刚入坑的&nbsp; 一次安装器都没成功启动过&nbsp; 都是一下闪退&nbsp; &nbsp;手动路径咱也确认过&nbsp; 输不输都一样


兰林
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LocalizeLimbusCompany/LLC_MOD_Toolbox"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月3日(星期四) 下午5:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LocalizeLimbusCompany/LLC_MOD_Toolbox] 启动器打开后几秒自动闪退   按照提供的解决办法自己写的游戏启动路径还是不行 (Issue #74)





 
OneDrive和GitHub上的启动器文件没有实质性区别，另外您从GitHub下载的是源码而不是启动器（下载错了），如果您仍然信不过OneDrive方面的话请去“Release”界面才能下载到真正的启动器。
 
和其他人的文件区别不是您下载文件缺失的问题。一些文件是首次运行后生成的，所以有一些不太重要的区别不必担心。
 
问一下您之前有成功运行过v1.0.0以上的安装器吗？
  
如果没有，可能是您的系统兼容性问题，或者是您写的路径不对/有语法错误/忘记保存？
 image.png (view on web)
 
如果有，这个问题就……比较玄学，可能也跟系统有关，其他人也曾有过突然无法使用的类似情况，可以稍等几天后再试试。
  
 
另外如果您急用模组，推荐参考模组的手动安装方式。

**Comment by ZengXiaoPi** [comment]
你修改CskipLCBPathCheck项了吗

**Comment by N071** [comment]
- 如果不熟悉GitHub，则不必强求使用GitHub。我们提供OneDrive就是为了帮助其他人绕开GitHub的。
  - OneDrive上的文件和GitHub上的文件**并无不同。**
- 麻烦您再仔细查看文档站内的教程，尽量不要漏掉步骤

**Comment by N071** [comment]
如果您实在不能使用安装器，我们其实也感到非常抱歉和遗憾。我们会尽力完善它，但有些问题我们解决起来也并不简单。对于这些问题我们也百思不得其解，只能退而求其次给出一些绕过的方案。

请注意，安装器只是一个简化安装流程的工具，**并不是安装的唯一渠道。**您可以尝试着进行手动安装，能够达成相同效果，其安装与更新流程都并不复杂。

**Comment by qingfeng6897** [comment]
> 你修改CskipLCBPathCheck项了吗

完完整整改好了的

**Comment by qingfeng6897** [comment]
> 如果您实在不能使用安装器，我们其实也感到非常抱歉和遗憾。我们会尽力完善它，但有些问题我们解决起来也并不简单。对于这些问题我们也百思不得其解，只能退而求其次给出一些绕过的方案。
> 
> 请注意，安装器只是一个简化安装流程的工具， **并不是安装的唯一渠道。** 您可以尝试着进行手动安装，能够达成相同效果，其安装与更新流程都并不复杂。

主要是常见问题解决办法里提供的工具箱箱出问题的解决方式就重装 关防火墙给软件权限  还有手动填写启动路径  我都仔细搞了  还反复重装重新改了好几遍 都不当用 最后报告一下问题去手动安装了
