### ISSUE TITLE
关闭模组按钮无法使用，疑似与百度输入法冲突

### ISSUE THREAD

**Issue by funlun2022** [LocalizeLimbusCompany/LLC_MOD_Toolbox#75]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

安装器版本1.0.1，反正是刚不久下的最新版。
在按下模组开关按钮后，安装器会卡死。未响应。随后自行关闭。同时百度输入法也会发个弹窗凑热闹。
之前一直用得是1.0.0似乎没有这个情况来着（）
看了下1.0.1的更新日志，模组开关更新了（）

### 日志文件

[Log-20241003.log](https://github.com/user-attachments/files/17243692/Log-20241003.log)

### 截图

![bandicam 2024-10-03 19-50-24-406](https://github.com/user-attachments/assets/6859403c-9ddd-4d90-a9a1-baf32533b6df)
![bandicam 2024-10-03 19-50-28-718](https://github.com/user-attachments/assets/bc00a951-7c66-4cdb-9815-33c65c8699d5)

### 还有别的吗？

win10
百度输入法TFS6.1.10.7
安装器1.0.1

**Comment by funlun2022** [comment]
哦？
百度输入法也有日志
[bddump_X64LLC_MOD_Toolbox.exe_PID=13336_TID=12424_TIMESTAMP=742929357.dmp.txt](https://github.com/user-attachments/files/17243993/bddump_X64LLC_MOD_Toolbox.exe_PID.13336_TID.12424_TIMESTAMP.742929357.dmp.txt)
看不懂。
希望能起到帮助

**Comment by funlun2022** [comment]
> 哦？ 百度输入法也有日志 [bddump_X64LLC_MOD_Toolbox.exe_PID=13336_TID=12424_TIMESTAMP=742929357.dmp.txt](https://github.com/user-attachments/files/17243993/bddump_X64LLC_MOD_Toolbox.exe_PID.13336_TID.12424_TIMESTAMP.742929357.dmp.txt) 看不懂。 希望能起到帮助

这个日志把我盒了！c

**Comment by ZengXiaoPi** [comment]
工具箱没有获取到正确路径。
下个版本会有所缓解。

**Comment by funlun2022** [comment]
谢谢啦
________________________________
发件人: 曾小皮-ZengXiaoPi ***@***.***>
发送时间: 2024年10月3日 20:56
收件人: LocalizeLimbusCompany/LLC_MOD_Toolbox ***@***.***>
抄送: funlun2022 ***@***.***>; Author ***@***.***>
主题: Re: [LocalizeLimbusCompany/LLC_MOD_Toolbox] 关闭模组按钮无法使用，疑似与百度输入法冲突 (Issue #75)


工具箱没有获取到正确路径。
下个版本会有所缓解。

―
