### ISSUE TITLE
"不知道这样的主机”

### ISSUE THREAD

**Issue by F4ust-hex** [LocalizeLimbusCompany/LLC_MOD_Toolbox#76]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动安装汉化模组后会出现“不知道这样的主机”错误

### 日志文件

[Log-20241005.log](https://github.com/user-attachments/files/17266118/Log-20241005.log)

### 还有别的吗？

麻烦了，谢谢

**Comment by ZengXiaoPi** [comment]
参考官网手动设置路径。

**Comment by F4ust-hex** [comment]
更改完路径保存后打开工具箱仍显示相同的错误
