### ISSUE TITLE
找到了如#66号问题出现winhttp.dll不存在的出现原因

### ISSUE THREAD

**Issue by AsrieIDreemurr** [LocalizeLimbusCompany/LLC_MOD_Toolbox#78]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

当模组在工具箱中关闭后，点击安装模组出现winhttp.dll不存在的提示，打开模组后再点击安装模组，模组正常安装，认为不存在winhttp.dll弹窗还可能因为模组的关闭而出现，建议增加新弹窗避免误解

### 日志文件

[Log-20241011.log](https://github.com/user-attachments/files/17340018/Log-20241011.log)

### 截图

![image](https://github.com/user-attachments/assets/a9bada1e-3ce7-452c-9ff8-83fe7fad966d)

**Comment by N071** [comment]
感谢！这部分的安装逻辑会在下个版本受到优化，以使得在关闭模组的情况下也能够进行更新！
