### ISSUE TITLE
安装器报错

### ISSUE THREAD

**Issue by yangyz2000** [LocalizeLimbusCompany/LLC_MOD_Toolbox#8]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

安装器如图所示报错，然后打开安装器后按钮全部为灰色无法点击

### 日志文件

[LLCToolBox_log.txt](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/files/11683491/LLCToolBox_log.txt)

### 截图

![`%%NF2DJ1%Z`$Y G)}%96DG](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/134857049/6761d8e1-1d9c-4f52-983d-b26f42b0247b)

**Comment by Bright1192** [comment]
根据log显示，你无法访问任何一个镜像站
不过既然你能来到这里发issue，这意味着你可以尝试把使用GitHub选项打开

**Comment by yangyz2000** [comment]
hhh我人在日本，应该不是网络问题，所以要怎样解决呢

**Comment by ZengXiaoPi** [comment]
打开使用Github选项

**Comment by yangyz2000** [comment]
但是我的安装器打开之后所有的按钮点击之后都没有反应，所以打开不了。。

**Comment by ZengXiaoPi** [comment]
这是一个保护措施，在你点击一键安装后无法点击选项，你需要在点击使用Github后点击一键安装。

**Comment by yangyz2000** [comment]
![IZK5N)(C8 }0L@JLC235%VY](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/assets/134857049/d7da6463-2b74-4354-ab66-0479e57a4f75)
可是这个界面什么都点不了，我也点不了使用github以及一键安装，点了没反应

**Comment by ZengXiaoPi** [comment]
> ![IZK5N)(C8 }0L@JLC235%VY](https://user-images.githubusercontent.com/134857049/246290142-d7da6463-2b74-4354-ab66-0479e57a4f75.png) 可是这个界面什么都点不了，我也点不了使用github以及一键安装，点了没反应

使用手动安装
