### ISSUE TITLE
模组跑代码时闪退无法进入游戏

### ISSUE THREAD

**Issue by yyyyyy210** [LocalizeLimbusCompany/LLC_MOD_Toolbox#83]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

和之前一位用户一样模组在开始跑代码时闪退无法进入游戏，手动安装，文件覆盖都尝试过无法解决问题，目前多天持续如此尚未解决。

### 日志文件

![Uploading 376581765-a3164081-0f72-4b5a-9529-7a33bdf45657.png…]()

**Comment by ZengXiaoPi** [comment]
`Uploading 376581765-a3164081-0f72-4b5a-9529-7a33bdf45657.png…`
你并没有提供有效的截图，并且此处你应该放置的是**日志文件**，而不是**截图**
截图应当放在下面一栏
反馈问题必须带上**日志**，否则我无法给予**任何帮助**

**Comment by yyyyyy210** [comment]
很抱歉未能准确的指出关键点而带来的不必要的麻烦，因为本人是电脑新人之前并未过多接触这类东西可能一些词语如日志文件一类的专业名词不太了解，电脑截图也是一塌糊涂，这次我去搜索了一下并重新提交了一份问题反馈，如有不对的地方还请指出。希望这份修改过的反馈对您有帮助。 ---- 回复的原邮件 ---- 发件人 ***@***.***> 日期 2024年10月17日 20:57 收件人 ***@***.***> 抄送至 ***@***.***>***@***.***> 主题 Re: [LocalizeLimbusCompany/LLC_MOD_Toolbox] 模组跑代码时闪退无法进入游戏 (Issue #83) Uploading 376581765-a3164081-0f72-4b5a-9529-7a33bdf45657.png… 你并没有提供有效的截图，并且此处你应该放置的是日志文件，而不是截图 截图应当放在下面一栏 反馈问题必须带上日志，否则我无法给予任何帮助 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>
