### ISSUE TITLE
模组跑代码时闪退无法进入游戏

### ISSUE THREAD

**Issue by yyyyyy210** [LocalizeLimbusCompany/LLC_MOD_Toolbox#84]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

和之前一位用户的情况一样，工具箱可以正常打开，但是模组刚运行时闪退无法进入游戏，关闭模组后可以正常进入游戏，重新安装和手动安装以及文件覆盖都尝试过无法解决问题。

### 日志文件

[Log-20241018.log20241018.log](https://github.com/user-attachments/files/17427258/Log-20241018.log20241018.log)
[Log-20241018.log](https://github.com/user-attachments/files/17427261/Log-20241018.log)
[Log-20241017.log](https://github.com/user-attachments/files/17427262/Log-20241017.log)

### 截图

![image](https://github.com/user-attachments/assets/9487d532-729d-418e-87fc-9d091ade9e4a)

**Comment by ZengXiaoPi** [comment]
尝试重新安装。
