### ISSUE TITLE
关闭杀软后也无法下载汉化

### ISSUE THREAD

**Issue by KunMNX** [LocalizeLimbusCompany/LLC_MOD_Toolbox#85]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

关闭杀软后也无法下载汉化

### 日志文件

无

### 截图

![屏幕截图(235)](https://github.com/user-attachments/assets/9e68dfcf-3bbb-4dbd-b105-c2e119d38fb5)

**Comment by ZengXiaoPi** [comment]
“日志文件 无”

**Comment by ZengXiaoPi** [comment]
我需要说明的是，日志文件一栏标为**Required**，意义就是，你必须上传**最新，有效**的日志，或者说明自己无法上传日志的理由，而不是让你填写一个毫无意义的**无**。

**Comment by KunMNX** [comment]
[Player(游戏日志).log](https://github.com/user-attachments/files/17477416/Player.log)

**Comment by KunMNX** [comment]
抱歉浪费了时间

**Comment by ZengXiaoPi** [comment]
`上传 /Logs 目录下的最新日志文件
请直接将完整的文件拖拽进来，而非自己裁切的片段；若文件体积过大可压缩后再上传`

**Comment by KunMNX** [comment]
未进行裁剪是一整个文件
[Player(游戏日志).log](https://github.com/user-attachments/files/17477562/Player.log)

**Comment by KunMNX** [comment]
已是最新游戏登录日志

**Comment by KunMNX** [comment]
我是否需要再次登录游戏上传更新后的日志

**Comment by ZengXiaoPi** [comment]
**工具箱目录/Logs/最新的日志.log**
拖到这个Issue，上传

**Comment by KunMNX** [comment]
[Log-20241022.log](https://github.com/user-attachments/files/17477672/Log-20241022.log)

**Comment by ZengXiaoPi** [comment]
重复议题 #66 #78

**Comment by KunMNX** [comment]
谢谢

**Comment by KunMNX** [comment]
抱歉浪费时间了，我的问题
