### ISSUE TITLE
一直无法安装

### ISSUE THREAD

**Issue by MARANDCRY** [LocalizeLimbusCompany/LLC_MOD_Toolbox#86]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更换节点还是报错，重新安装也还是这样子

### 日志文件

[Log-20241030.log](https://github.com/user-attachments/files/17570436/Log-20241030.log)

**Comment by ZengXiaoPi** [comment]
尝试更换API节点，如果还不行的话就是无解，手动安装吧
