### ISSUE TITLE
 链接失败

### ISSUE THREAD

**Issue by Wkzszk** [LocalizeLimbusCompany/LLC_MOD_Toolbox#87]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

链接失败，在换了几次节点，开关模组后都安装失败

### 日志文件

[Log-20241105.log20241105.log](https://github.com/user-attachments/files/17627157/Log-20241105.log20241105.log)

### 截图

![PVQB51W{ 4 BI40QU3W01(K](https://github.com/user-attachments/assets/b21b7c87-8e37-4a40-b296-35a75e95594c)
![SJDCH{V~(B$NPE%CB@_LCJJ](https://github.com/user-attachments/assets/5f99dde3-2bdd-44e1-b018-cc9ad44578f7)

**Comment by N071** [comment]
网络问题。
请尝试更换节点或API节点，可以试着尝试使用GitHub节点。
如果依旧无法解决，则可能无法使用我们提供的服务。此种情况下建议参考手动安装，也并不复杂。
