### ISSUE TITLE
无法安装/安装报错

### ISSUE THREAD

**Issue by DEARMED** [LocalizeLimbusCompany/LLC_MOD_Toolbox#88]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

安装工具箱后报错，且重装后依旧无法安装

### 日志文件

[Log-20241109.log](https://github.com/user-attachments/files/17685511/Log-20241109.log)

### 截图

![Uploading f29fbd53-6179-4fff-87f7-d17cd3ce03f2.png…]()

**Comment by ZengXiaoPi** [comment]
![image](https://github.com/user-attachments/assets/0752a827-efd4-415e-885f-6d432849af63)
你选择了错误的边狱公司地址。
