### ISSUE TITLE
汉化mod安装出错

### ISSUE THREAD

**Issue by HtcOP-1** [LocalizeLimbusCompany/LLC_MOD_Toolbox#89]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

汉化mod安装出错，切换节点都一样

### 日志文件

[Log-20241118.log](https://github.com/user-attachments/files/17791308/Log-20241118.log)

### 截图

![image](https://github.com/user-attachments/assets/7802b03f-a7ad-4b39-a73b-04248c65f826)

**Comment by ZengXiaoPi** [comment]
你的边狱公司路径在`D:\steam\steamapps\common\Limbus Company`吗

**Comment by HtcOP-1** [comment]
在的
![image](https://github.com/user-attachments/assets/583c1e66-89c0-43c1-b9a3-09e3fa642eaa)

**Comment by ZengXiaoPi** [comment]
事实上，你不需要把工具箱和边狱公司混合在一起
但是我也没法从日志里看出来什么，所以没法解决

**Comment by HtcOP-1** [comment]
啊 好吧 还是谢谢大佬了 我再试试其他方法
