### ISSUE TITLE
请问如何打开sln文件

### ISSUE THREAD

**Issue by s441764347** [LocalizeLimbusCompany/LLC_MOD_Toolbox#9]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

已经安装了链接指向的.NET框架，解压文件中的LLC_MOD_Toolbox.sln无程序类型能打开，请问该如何运行

### 日志文件

已经安装了链接指向的.NET框架，解压文件中的LLC_MOD_Toolbox.sln无程序类型能打开，请问该如何运行

**Comment by Bright1192** [comment]
**通常**来讲，你不应该去下载`Code`，应该去`Releases`下载`第1个`文件
如果你不明白这些是干什么的，则无论如何您不应该去尝试打开`源代码`
