### ISSUE TITLE
工具箱只会在第一次使用检测边狱巴士文件地址

### ISSUE THREAD

**Issue by AsrieIDreemurr** [LocalizeLimbusCompany/LLC_MOD_Toolbox#90]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

现在的工具箱只会在第一次启动时检测一次边狱巴士的地址并写入config.json，工具箱内没有修改或重新检测的手段。
我于前段时间大规模网络问题时重新安装了边狱巴士，意外的放到了另一个地址，此后重新安装汉化没用，排查后发现是工具箱安装把模组到了另一个位置，后通过删除config.json解决问题。

### 日志文件

我确定不需要Logs

### 截图

![Image_1732364292023](https://github.com/user-attachments/assets/8a66b4ce-d598-48ec-a310-9c24ff07a12c)

**Comment by AsrieIDreemurr** [comment]
起码该加到文档常见问题里面，先翻的常见问题没找到

**Comment by ZengXiaoPi** [comment]
这不属于常见情况，一般来说我不认为会有人总是更换游戏路径，因此在首次启动才会询问你的游戏路径

**Comment by AsrieIDreemurr** [comment]
好吧，但我认为要是没什么电脑基础的人遇到这种情况可能就完全束手无策了

**Comment by N071** [comment]
我们的安装器也是慢慢完善的，因此在一些事情上会有些疏忽。一般来讲我们会推荐用户进行完全删除再重装，虽然不够优雅，但能解决包括这个问题在内的绝大多数问题，大概也不能算是束手无策吧。
不过，针对这个情况 我相信小皮后续优化相关逻辑应该不难。

我们提供安装器的初衷只是优化安装方式，如果安装器这条路走不通，也不应该忘记还有手动安装这一方案便是。

之前[#78](https://github.com/LocalizeLimbusCompany1_MOD_Toolbox/issues/78)的建议也是来自于你的，我们在之后就优化了相关逻辑。很感谢你提出的各个问题。
