### ISSUE TITLE
游戏无法进入

### ISSUE THREAD

**Issue by whitekaxi** [LocalizeLimbusCompany/LLC_MOD_Toolbox#94]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

启动游戏后提示，如图片所示的窗口，然后无法进入游戏，卸载汉化模组依旧呈现同样的问题

### 日志文件

[Log-20241130.log](https://github.com/user-attachments/files/17964620/Log-20241130.log)

### 截图

![image](https://github.com/user-attachments/assets/7a61a6cd-aa18-4337-9f13-1b154555b457)
![image](https://github.com/user-attachments/assets/edfc4333-4a04-4140-b35a-1eecd88bf428)

**Comment by ZengXiaoPi** [comment]
删除游戏目录所有文件，随后检查游戏完整性，完成后再次安装工具箱
