### ISSUE TITLE
汉化包在电脑重启后失效

### ISSUE THREAD

**Issue by VolTinethedoggy** [LocalizeLimbusCompany/LLC_MOD_Toolbox#95]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在首次安装工具箱及汉化包后均可以正常运行，但在电脑关机重启之后打开游戏时汉化包未生效，通过工具箱开关补丁以及删除重新下载后均未解决，并且电脑的杀毒软件等均已关闭

### 日志文件

[Log-20241130.log](https://github.com/user-attachments/files/17965551/Log-20241130.log)

**Comment by N071** [comment]
请试着比对是不是此问题：https://www.zeroasso.top/docs/FAQ#no-console
