### ISSUE TITLE
自动安装完成，游戏开启后控制台红字报错，游戏可进入， 但游戏内设置没有中文选项。

### ISSUE THREAD

**Issue by smithJerk** [LocalizeLimbusCompany/LLC_MOD_Toolbox#98]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

朋友第一次玩， 已经在使用安装器前确保了：
1，已经开启过一次游戏确保开生成的文件生成完毕
2，进入过游戏完成游戏内置更新，可以进入序章避免文件包不全。

但是在使用自动安装器时，  首次开启时报错无法找到游戏（已附图）
手动选择了游戏目录后， 自动安装， 安装器没有再报错。

开启游戏以后， 控制台会报错（如图）， 游戏内进入小齿轮 也只有韩英日三个语言选项。  

目前已经优先排查过的问题：
1， 游戏根目录的确有生成Bpinex文件夹，确保不是因为安装路径选择错误造成出错。
2， 猜测控制台象形文字乱码是否是因为非unicode语言设置不正常导致，调查过系统的非Unicode程序语言是中文（简体，中国）
3， 猜测控制台象形文字乱码是否是因为缺少font文件导致的， 但是发现好像并不相关。

朋友很想玩，但是他英文不太好， 我挠头了半天并看不明白是什么问题。 求助

### 日志文件

[LogOutput.log](https://github.com/user-attachments/files/18106792/LogOutput.log)

### 截图

![ec20f11289e2b7e4eaf738c56bf9e3e6](https://github.com/user-attachments/assets/3a1643b2-326c-4fb8-9bda-5e5d0c7806e5)
![7d5ab8e7032ace378ca7027b44c5e586](https://github.com/user-attachments/assets/f1f7fda8-9801-4bf1-8458-630d1ceae343)

### 还有别的吗？

win11
尝试了一下手动安装，  个人有很多打mod经历，手动安装时应该没有任何步骤错误
但依然是一样的报错

**Comment by mucketguct** [comment]
您好，今天在更新后发生的汉化失效状况，是因为月亮计划在本次更新中大改了文本的显示逻辑，导致模组文本目前暂时无法正常显示，目前正在尝试修复中啦，详情可以参见今天上午发布的最新动态--可以在下次模组更新动态发布后，通过工具箱自动更新模组，有可能就没问题啦

**Comment by mucketguct** [comment]
另外如果在下次更新模组后，依然遇到同一报错弹窗的话，这种情况有可能与游戏本体的路径有关，可以先尝试删除一次边狱公司的游戏本体，然后把游戏本体的安装路径换到C盘，再安装游戏本体，有可能可以解决此问题；

该问题也有可能是网络问题，可以尝试更换一下网络环境，也可以尝试在工具箱的“设置”栏中，切换节点后再尝试安装模组；

另外该问题也有可能在重启一次电脑后自行消失，总之先祝顺利啦

**Comment by smithJerk** [comment]
感激， 等一波更新看看。

**Comment by N071** [comment]
1. 这里是Toolbox的repo，并不是LLC模组repo。模组问题不应该在安装器repo这边发issue
2. 关注我们的B站账号，如果模组更新后出现问题我们会提供消息。在发Issue之前请务必确认我们是否已经有提前告知

**Comment by smithJerk** [comment]
了解

就此次来说表单发错地方来说， 是因为我的知识储备并不支持我去确定错误的原因和汉化的哪一部分关系更大， 所以我选择了在我所能触及的地方寻求帮助

我刚刚已经关注了B站账号，看到了新更新造成问题的动态。以后也会持续关注。

**Comment by N071** [comment]
> 了解
> 
> 就此次表单发错地方来说， 是因为我的知识储备并不支持我去确定错误的原因和汉化的哪一部分关系更大， 所以我选择了在我所能触及的地方寻求帮助
> 
> 我刚刚已经关注了B站账号，看到了新更新造成问题的动态。以后也会持续关注。

小事，你突然这么讲搞得我们也不好意思了xD

**Comment by smithJerk** [comment]
还是要谢谢汉化工作者们
我因为个人原因， 一直以来玩LC并没有使用汉化，所以并没有安装经验。
但是今天终于把游戏成功推荐给了好友， 但是正好遇到了更新出问题，所以摸不着头脑很着急。
能有更多的月计人真的太好了。
