### ISSUE TITLE
安装过程中发生报错system.io.filenotfoundexception

### ISSUE THREAD

**Issue by bdmhy** [LocalizeLimbusCompany/LLC_MOD_Toolbox#99]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在下载安装进度条未过半时弹出该报错，不排除是网络原因，但我换了不少梯子也未解决

### 日志文件

[Log-20241212.log](https://github.com/user-attachments/files/18108304/Log-20241212.log)

### 截图

![5E}AX45ZG}KKWPBK(8{`BAL](https://github.com/user-attachments/assets/5983a582-495d-45b1-ba5d-9ae527554950)

**Comment by ZengXiaoPi** [comment]
请尝试切换节点，关闭加速器
